# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
GENERATED_IUSE="pyexecjs pymongo"
IUSE="${GENERATED_IUSE}"

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/mongomock/"

LICENSE=""
SLOT="0"
KEYWORDS="amd64 arm64"

REQUIRES_DIST="
	packaging
	pyexecjs; extra == 'pyexecjs'
	pymongo; extra == 'pymongo'
	pytz
	sentinels
"
GENERATED_RDEPEND="${RDEPEND}
	dev-python/packaging[${PYTHON_USEDEP}]
	pyexecjs? ( dev-python/pyexecjs[${PYTHON_USEDEP}] )
	pymongo? ( dev-python/pymongo[${PYTHON_USEDEP}] )
	dev-python/pytz[${PYTHON_USEDEP}]
	dev-python/sentinels[${PYTHON_USEDEP}]
"
RDEPEND="${GENERATED_RDEPEND}"

distutils_enable_tests pytest
