# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
GENERATED_IUSE="test xarray"
IUSE="${GENERATED_IUSE}"

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/cfgrib/"

LICENSE=""
SLOT="0"
KEYWORDS="amd64 arm64"

REQUIRES_DIST="
	attrs>=19.2
	click
	dask[array]; extra == 'tests'
	eccodes>=0.9.8
	flake8; extra == 'tests'
	numpy
	pytest-cov; extra == 'tests'
	pytest; extra == 'tests'
	scipy; extra == 'tests'
	xarray>=0.15; extra == 'tests'
	xarray>=0.15; extra == 'xarray'
"
GENERATED_RDEPEND="${RDEPEND}
	>=dev-python/attrs-19.2[${PYTHON_USEDEP}]
	dev-python/click[${PYTHON_USEDEP}]
	>=dev-python/eccodes-0.9.8[${PYTHON_USEDEP}]
	dev-python/numpy[${PYTHON_USEDEP}]
	xarray? ( >=dev-python/xarray-0.15[${PYTHON_USEDEP}] )
"
RDEPEND="${GENERATED_RDEPEND}"

distutils_enable_tests pytest
GENERATED_BDEPEND="${BDEPEND}
	test? (
		dev-python/dask[array,${PYTHON_USEDEP}]
		dev-python/flake8[${PYTHON_USEDEP}]
		dev-python/pytest[${PYTHON_USEDEP}]
		dev-python/pytest-cov[${PYTHON_USEDEP}]
		dev-python/scipy[${PYTHON_USEDEP}]
		>=dev-python/xarray-0.15[${PYTHON_USEDEP}]
	)
"
BDEPEND="${GENERATED_BDEPEND}"
