# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/ridgeplot/"

LICENSE=""
SLOT="0"
KEYWORDS="amd64 arm64"

REQUIRES_DIST="
	importlib-resources; python_version < '3.10'
	numpy>=1
	plotly>=5.20
	statsmodels!=0.14.2,>=0.12
	typing-extensions
"
GENERATED_RDEPEND="${RDEPEND}
	>=dev-python/numpy-1[${PYTHON_USEDEP}]
	>=dev-python/plotly-5.20[${PYTHON_USEDEP}]
	>=dev-python/statsmodels-0.12[${PYTHON_USEDEP}] !~dev-python/statsmodels-0.14.2[${PYTHON_USEDEP}]
	dev-python/typing-extensions[${PYTHON_USEDEP}]
"
RDEPEND="${GENERATED_RDEPEND}"

distutils_enable_tests pytest
