# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/dython/"

LICENSE="MIT"
SLOT="0"
KEYWORDS="amd64 arm64"

REQUIRES_DIST="
	black>=24.8.0; extra == 'dev'
	hypothesis>=6.111.0; extra == 'dev'
	matplotlib>=3.6.0
	numpy>=1.23.0
	pandas>=1.4.2
	pre-commit>=3.8.0; extra == 'dev'
	psutil>=5.9.1
	pytest-enabler>=3.1.1; extra == 'dev'
	pytest>=8.3.2; extra == 'dev'
	scikit-learn>=0.24.2
	scipy>=1.7.1
	seaborn>=0.12.0
	setuptools
"
GENERATED_RDEPEND="${RDEPEND}
	>=dev-python/matplotlib-3.6.0[${PYTHON_USEDEP}]
	>=dev-python/numpy-1.23.0[${PYTHON_USEDEP}]
	>=dev-python/pandas-1.4.2[${PYTHON_USEDEP}]
	>=dev-python/psutil-5.9.1[${PYTHON_USEDEP}]
	>=dev-python/scikit-learn-0.24.2[${PYTHON_USEDEP}]
	>=dev-python/scipy-1.7.1[${PYTHON_USEDEP}]
	>=dev-python/seaborn-0.12.0[${PYTHON_USEDEP}]
	dev-python/setuptools[${PYTHON_USEDEP}]
"
RDEPEND="${GENERATED_RDEPEND}"

distutils_enable_tests pytest
GENERATED_BDEPEND="${BDEPEND}
	test? (
		>=dev-python/black-24.8.0[${PYTHON_USEDEP}]
		>=dev-python/hypothesis-6.111.0[${PYTHON_USEDEP}]
		>=dev-python/pytest-8.3.2[${PYTHON_USEDEP}]
		>=dev-python/pytest-enabler-3.1.1[${PYTHON_USEDEP}]
		>=dev-vcs/pre-commit-3.8.0[${PYTHON_USEDEP}]
	)
"
BDEPEND="${GENERATED_BDEPEND}"
