# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
PYPI_NO_NORMALIZE=1
GENERATED_IUSE="all numpy test"
IUSE="${GENERATED_IUSE}"

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/h3/"

LICENSE=""
SLOT="0"
KEYWORDS="amd64 arm64"

GENERATED_DEPEND="
	all? ( dev-python/cartopy[${PYTHON_USEDEP}] )
	all? ( dev-python/contextily[${PYTHON_USEDEP}] )
	test? ( dev-python/flake8[${PYTHON_USEDEP}] )
	all? ( dev-python/geodatasets[${PYTHON_USEDEP}] )
	all? ( dev-python/geopandas[${PYTHON_USEDEP}] )
	all? ( dev-python/geoviews[${PYTHON_USEDEP}] )
	all? ( dev-python/h3[test,${PYTHON_USEDEP}] )
	all? ( dev-python/jupyter-book[${PYTHON_USEDEP}] )
	all? ( dev-python/jupyterlab[${PYTHON_USEDEP}] )
	all? ( dev-python/jupyterlab-geojson[${PYTHON_USEDEP}] )
	all? ( dev-python/matplotlib[${PYTHON_USEDEP}] )
	numpy? ( dev-python/numpy[${PYTHON_USEDEP}] )
	test? ( dev-python/numpy[${PYTHON_USEDEP}] )
	test? ( dev-python/pylint[${PYTHON_USEDEP}] )
	test? ( dev-python/pytest[${PYTHON_USEDEP}] )
	test? ( dev-python/pytest-cov[${PYTHON_USEDEP}] )
	all? ( >=dev-python/sphinx-7.3.3[${PYTHON_USEDEP}] )
"
RDEPEND="${GENERATED_DEPEND}"

distutils_enable_tests pytest