# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
GENERATED_IUSE="all doc lint test"
IUSE="${GENERATED_IUSE} +build"

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/scikit-misc/"

LICENSE=""
SLOT="0"
KEYWORDS="amd64 arm64"

REQUIRES_DIST="
	build; extra == 'build'
	cython; extra == 'build'
	meson-python; extra == 'build'
	meson; extra == 'build'
	ninja; extra == 'build'
	numpy>=1.23.5
	numpydoc; extra == 'doc'
	pytest-cov; extra == 'test'
	ruff; extra == 'lint'
	scikit-misc[build]; extra == 'all'
	scikit-misc[dev]; extra == 'all'
	scikit-misc[doc]; extra == 'all'
	scikit-misc[lint]; extra == 'all'
	scikit-misc[test]; extra == 'all'
	sphinx; extra == 'doc'
	spin; extra == 'build'
	twine; extra == 'dev'
	wheel; extra == 'dev'
"
GENERATED_RDEPEND="${RDEPEND}
	>=dev-python/numpy-1.23.5[${PYTHON_USEDEP}]
	doc? ( dev-python/numpydoc[${PYTHON_USEDEP}] )
	lint? ( dev-python/ruff[${PYTHON_USEDEP}] )
	all? ( dev-python/scikit-misc[build,${PYTHON_USEDEP}] )
	all? ( dev-python/scikit-misc[dev,${PYTHON_USEDEP}] )
	all? ( dev-python/scikit-misc[doc,${PYTHON_USEDEP}] )
	all? ( dev-python/scikit-misc[lint,${PYTHON_USEDEP}] )
	all? ( dev-python/scikit-misc[test,${PYTHON_USEDEP}] )
	doc? ( dev-python/sphinx[${PYTHON_USEDEP}] )
"
RDEPEND="${GENERATED_RDEPEND}"

distutils_enable_tests pytest
GENERATED_BDEPEND="${BDEPEND}
	dev-build/meson[${PYTHON_USEDEP}]
	dev-python/build[${PYTHON_USEDEP}]
	dev-python/cython[${PYTHON_USEDEP}]
	dev-python/meson-python[${PYTHON_USEDEP}]
	dev-build/ninja[${PYTHON_USEDEP}]
	dev-python/spin[${PYTHON_USEDEP}]
	test? (
		dev-python/pytest-cov[${PYTHON_USEDEP}]
		dev-python/twine[${PYTHON_USEDEP}]
		dev-python/wheel[${PYTHON_USEDEP}]
	)
"
BDEPEND="${GENERATED_BDEPEND}"
