# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
PYPI_NO_NORMALIZE=1
GENERATED_IUSE="tests"
IUSE="${GENERATED_IUSE}"

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/dvc-http/"

LICENSE=""
SLOT="0"
KEYWORDS="amd64 arm64"

GENERATED_DEPEND="${PYTHON_DEPS}
	>=dev-python/aiohttp-retry-2.5.0[${PYTHON_USEDEP}]
	tests? ( dev-python/dvc[testing,${PYTHON_USEDEP}] )
	tests? ( ~dev-python/flaky-3.7.0[${PYTHON_USEDEP}] )
	dev-python/fsspec[http,${PYTHON_USEDEP}]
	tests? ( ~dev-python/mypy-0.910[${PYTHON_USEDEP}] )
	tests? ( ~dev-python/pylint-2.15.9[${PYTHON_USEDEP}] )
	tests? ( ~dev-python/pytest-6.2.5[${PYTHON_USEDEP}] )
	tests? ( ~dev-python/pytest-cov-3.0.0[${PYTHON_USEDEP}] )
	tests? ( ~dev-python/pytest-mock-3.6.1[${PYTHON_USEDEP}] )
	tests? ( ~dev-python/pytest-xdist-2.4.0[${PYTHON_USEDEP}] )
	tests? ( ~dev-python/rangehttpserver-1.2.0[${PYTHON_USEDEP}] )
	tests? ( ~dev-python/types-requests-2.25.11[${PYTHON_USEDEP}] )
"
RDEPEND="${GENERATED_DEPEND}"

distutils_enable_tests pytest
