# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
GENERATED_IUSE="all test"
IUSE="${GENERATED_IUSE}"

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/lfdfiles/"

LICENSE="BSD"
SLOT="0"
KEYWORDS="amd64 arm64"

REQUIRES_DIST="
	click
	czifile; extra == 'all'
	imagecodecs; extra == 'all'
	matplotlib; extra == 'all'
	netpbmfile; extra == 'all'
	numpy
	oiffile; extra == 'all'
	pytest; extra == 'test'
	tifffile
"
GENERATED_RDEPEND="${RDEPEND}
	dev-python/click[${PYTHON_USEDEP}]
	all? ( dev-python/czifile[${PYTHON_USEDEP}] )
	all? ( dev-python/imagecodecs[${PYTHON_USEDEP}] )
	all? ( dev-python/matplotlib[${PYTHON_USEDEP}] )
	all? ( dev-python/netpbmfile[${PYTHON_USEDEP}] )
	dev-python/numpy[${PYTHON_USEDEP}]
	all? ( dev-python/oiffile[${PYTHON_USEDEP}] )
	dev-python/tifffile[${PYTHON_USEDEP}]
"
RDEPEND="${GENERATED_RDEPEND}"

distutils_enable_tests pytest
GENERATED_BDEPEND="${BDEPEND}
	test? (
		dev-python/pytest[${PYTHON_USEDEP}]
	)
"
BDEPEND="${GENERATED_BDEPEND}"
