# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
GENERATED_IUSE="cli"
IUSE="${GENERATED_IUSE}"

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/repo-review/"

LICENSE=""
SLOT="0"
KEYWORDS="amd64 arm64"

REQUIRES_DIST="
	click>=8; extra == 'cli'
	markdown-it-py
	pyyaml
	rich-click; extra == 'cli'
	rich>=12.2; extra == 'cli'
	tomli; python_version < '3.11'
	typing-extensions; python_version < '3.11'
"
GENERATED_RDEPEND="${RDEPEND}
	cli? ( >=dev-python/click-8[${PYTHON_USEDEP}] )
	dev-python/markdown-it-py[${PYTHON_USEDEP}]
	dev-python/pyyaml[${PYTHON_USEDEP}]
	cli? ( >=dev-python/rich-12.2[${PYTHON_USEDEP}] )
	cli? ( dev-python/rich-click[${PYTHON_USEDEP}] )
"
RDEPEND="${GENERATED_RDEPEND}"

distutils_enable_tests pytest
