# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
GENERATED_IUSE="docs zodb"
IUSE="${GENERATED_IUSE}"

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/btrees/"

LICENSE=""
SLOT="0"
KEYWORDS="amd64 arm64"

REQUIRES_DIST="
	Sphinx; extra == 'docs'
	ZODB; extra == 'zodb'
	persistent>=4.1.0
	persistent>=4.4.3; extra == 'test'
	repoze.sphinx.autointerface; extra == 'docs'
	sphinx_rtd_theme; extra == 'docs'
	transaction; extra == 'test'
	zope.interface>=5.0.0
	zope.testrunner; extra == 'test'
"
GENERATED_RDEPEND="${RDEPEND}
	>=dev-python/persistent-4.1.0[${PYTHON_USEDEP}]
	docs? ( dev-python/repoze-sphinx-autointerface[${PYTHON_USEDEP}] )
	docs? ( dev-python/sphinx[${PYTHON_USEDEP}] )
	docs? ( dev-python/sphinx-rtd-theme[${PYTHON_USEDEP}] )
	zodb? ( dev-python/zodb[${PYTHON_USEDEP}] )
	>=dev-python/zope-interface-5.0.0[${PYTHON_USEDEP}]
"
RDEPEND="${GENERATED_RDEPEND}"

distutils_enable_tests pytest
GENERATED_BDEPEND="${BDEPEND}
	test? (
		>=dev-python/persistent-4.4.3[${PYTHON_USEDEP}]
		dev-python/transaction[${PYTHON_USEDEP}]
		dev-python/zope-testrunner[${PYTHON_USEDEP}]
	)
"
BDEPEND="${GENERATED_BDEPEND}"
