# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/prometheus-fastapi-instrumentator/"

LICENSE="ISC"
SLOT="0"
KEYWORDS="amd64 arm64"

REQUIRES_DIST="
	prometheus-client<1.0.0,>=0.8.0
	starlette<1.0.0,>=0.30.0
"
GENERATED_RDEPEND="${RDEPEND}
	>=dev-python/prometheus-client-0.8.0[${PYTHON_USEDEP}] <dev-python/prometheus-client-1.0.0[${PYTHON_USEDEP}]
	>=dev-python/starlette-0.30.0[${PYTHON_USEDEP}] <dev-python/starlette-1.0.0[${PYTHON_USEDEP}]
"
RDEPEND="${GENERATED_RDEPEND}"

distutils_enable_tests pytest

