# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
GENERATED_IUSE="docs"
IUSE="${GENERATED_IUSE}"

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/dvc-studio-client/"

LICENSE="Apache-2.0"
SLOT="0"
KEYWORDS="amd64 arm64"

GENERATED_RDEPEND="${RDEPEND}
	dev-python/dulwich[${PYTHON_USEDEP}]
	docs? ( <dev-python/mkdocs-2[${PYTHON_USEDEP}] )
	docs? ( <dev-python/mkdocs-gen-files-1[${PYTHON_USEDEP}] )
	docs? ( <dev-python/mkdocs-material-10[${PYTHON_USEDEP}] )
	docs? ( <dev-python/mkdocs-section-index-1[${PYTHON_USEDEP}] )
	docs? ( <dev-python/mkdocstrings-python-2[${PYTHON_USEDEP}] )
	dev-python/requests[${PYTHON_USEDEP}]
	dev-python/voluptuous[${PYTHON_USEDEP}]
"
RDEPEND="${GENERATED_RDEPEND}"

distutils_enable_tests pytest
GENERATED_BDEPEND="${BDEPEND}
	test? (
		dev-python/dvc-studio-client[docs,tests,${PYTHON_USEDEP}]
		=dev-python/mypy-1.10.1[${PYTHON_USEDEP}]
		<dev-python/pytest-9[${PYTHON_USEDEP}]
		>=dev-python/pytest-cov-4.1.0[${PYTHON_USEDEP}]
		dev-python/pytest-mock[${PYTHON_USEDEP}]
		dev-python/pytest-sugar[${PYTHON_USEDEP}]
		dev-python/types-requests[${PYTHON_USEDEP}]
	)
"
BDEPEND="${GENERATED_BDEPEND}"
