# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
PYPI_NO_NORMALIZE=1
GENERATED_IUSE="all mutual-information visualization"
IUSE="${GENERATED_IUSE}"

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/tensorflow-data-validation/"

LICENSE=""
SLOT="0"
KEYWORDS="amd64 arm64"

GENERATED_DEPEND="${RDEPEND}
	<dev-python/absl-py-2.0.0[${PYTHON_USEDEP}]
	<dev-python/apache-beam-3[gcp,${PYTHON_USEDEP}]
	all? ( <dev-python/ipython-8[${PYTHON_USEDEP}] )
	visualization? ( <dev-python/ipython-8[${PYTHON_USEDEP}] )
	>=dev-python/joblib-1.2.0[${PYTHON_USEDEP}]
	>=dev-python/numpy-1.22.0[${PYTHON_USEDEP}]
	<dev-python/pandas-2[${PYTHON_USEDEP}]
	<dev-python/protobuf-6[${PYTHON_USEDEP}]
	<dev-python/pyarrow-11[${PYTHON_USEDEP}]
	<dev-python/pyfarmhash-0.4[${PYTHON_USEDEP}]
	all? ( <dev-python/scikit-learn-2[${PYTHON_USEDEP}] )
	mutual-information? ( <dev-python/scikit-learn-2[${PYTHON_USEDEP}] )
	all? ( <dev-python/scipy-2[${PYTHON_USEDEP}] )
	mutual-information? ( <dev-python/scipy-2[${PYTHON_USEDEP}] )
	<dev-python/six-2[${PYTHON_USEDEP}]
	<dev-python/tensorflow-2.17[${PYTHON_USEDEP}]
	<dev-python/tensorflow-metadata-1.17[${PYTHON_USEDEP}]
	<dev-python/tfx-bsl-1.17[${PYTHON_USEDEP}]
"
RDEPEND="${GENERATED_DEPEND}"

distutils_enable_tests pytest
