# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
GENERATED_IUSE="attrs"
IUSE="${GENERATED_IUSE}"

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/erdantic/"

LICENSE=""
SLOT="0"
KEYWORDS="amd64 arm64"

REQUIRES_DIST="
	attrs; extra == "attrs"
	pydantic-core
	pydantic>=2
	pygraphviz
	sortedcontainers-pydantic
	typenames>=1.3
	typer
	typing-extensions>4; python_version < "3.12"
"
GENERATED_RDEPEND="${RDEPEND}
	attrs? ( dev-python/attrs[${PYTHON_USEDEP}] )
	>=dev-python/pydantic-2[${PYTHON_USEDEP}]
	dev-python/pydantic-core[${PYTHON_USEDEP}]
	dev-python/pygraphviz[${PYTHON_USEDEP}]
	dev-python/sortedcontainers-pydantic[${PYTHON_USEDEP}]
	>=dev-python/typenames-1.3[${PYTHON_USEDEP}]
	dev-python/typer[${PYTHON_USEDEP}]
"
RDEPEND="${GENERATED_RDEPEND}"

distutils_enable_tests pytest
