# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
PYPI_NO_NORMALIZE=1
GENERATED_IUSE="all full style test"
IUSE="${GENERATED_IUSE}"

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/antio/"

LICENSE=""
SLOT="0"
KEYWORDS="amd64 arm64"

GENERATED_DEPEND="
	all? ( dev-python/antio[style,${PYTHON_USEDEP}] )
	all? ( dev-python/antio[test,${PYTHON_USEDEP}] )
	full? ( dev-python/antio[all,${PYTHON_USEDEP}] )
	dev-python/click[${PYTHON_USEDEP}]
	style? ( >=dev-python/codespell-2.2.4[toml,${PYTHON_USEDEP}] )
	test? ( dev-python/mne[${PYTHON_USEDEP}] )
	<dev-python/numpy-3[${PYTHON_USEDEP}]
	dev-python/packaging[${PYTHON_USEDEP}]
	dev-python/psutil[${PYTHON_USEDEP}]
	test? ( >=dev-python/pytest-8.0[${PYTHON_USEDEP}] )
	test? ( dev-python/pytest-cov[${PYTHON_USEDEP}] )
	style? ( >=dev-python/ruff-0.6.0[${PYTHON_USEDEP}] )
	style? ( dev-python/toml-sort[${PYTHON_USEDEP}] )
	style? ( dev-python/yamllint[${PYTHON_USEDEP}] )
"
RDEPEND="${GENERATED_DEPEND}"

distutils_enable_tests pytest