# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/ortools/"

LICENSE=""
SLOT="0"
KEYWORDS="amd64 arm64"

REQUIRES_DIST="
	absl-py>=2.0.0
	immutabledict>=3.0.0
	numpy>=1.13.3
	pandas>=2.0.0
	protobuf<5.30,>=5.29.3
"
GENERATED_RDEPEND="${RDEPEND}
	>=dev-python/absl-py-2.0.0[${PYTHON_USEDEP}]
	>=dev-python/immutabledict-3.0.0[${PYTHON_USEDEP}]
	>=dev-python/numpy-1.13.3[${PYTHON_USEDEP}]
	>=dev-python/pandas-2.0.0[${PYTHON_USEDEP}]
	>=dev-python/protobuf-5.29.3[${PYTHON_USEDEP}] <dev-python/protobuf-5.30[${PYTHON_USEDEP}]
"
RDEPEND="${GENERATED_RDEPEND}"

distutils_enable_tests pytest

