# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
PYPI_NO_NORMALIZE=1
GENERATED_IUSE="experimental"
IUSE="${GENERATED_IUSE}"

inherit distutils-r1
MY_PN=cudf
MY_PV=$(printf '%02d.%02d.%02d' ${PV//./ })
MY_P=${MY_PN}-${MY_PV}
SRC_URI="https://github.com/rapidsai/${MY_PN}/archive/refs/tags/v${MY_PV}.tar.gz -> ${MY_P}.gh.tar.gz"
S="${WORKDIR}/${MY_P}"

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/cudf-polars-cu12/"

LICENSE=""
SLOT="0"
KEYWORDS="amd64 arm64"

REQUIRES_DIST="
	numpy<3.0a0,>=1.23; extra == 'test'
	polars<1.15,>=1.11
	pylibcudf-cu12==24.12.*
	pytest-cov; extra == 'test'
	pytest-xdist; extra == 'test'
	pytest<8; extra == 'test'
	rapids-dask-dependency==24.12.*; extra == 'experimental'
"
GENERATED_RDEPEND="${RDEPEND}
	>=dev-python/polars-1.11[${PYTHON_USEDEP}] <dev-python/polars-1.15[${PYTHON_USEDEP}]
	=dev-python/pylibcudf-cu12-24.12*[${PYTHON_USEDEP}]
	experimental? ( =dev-python/rapids-dask-dependency-24.12*[${PYTHON_USEDEP}] )
"
RDEPEND="${GENERATED_RDEPEND}"

distutils_enable_tests pytest
GENERATED_BDEPEND="${BDEPEND}
	test? (
		>=dev-python/numpy-1.23[${PYTHON_USEDEP}] <dev-python/numpy-3.0_alpha0[${PYTHON_USEDEP}]
		<dev-python/pytest-8[${PYTHON_USEDEP}]
		dev-python/pytest-cov[${PYTHON_USEDEP}]
		dev-python/pytest-xdist[${PYTHON_USEDEP}]
	)
"
BDEPEND="${GENERATED_BDEPEND}"
