# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
PYPI_NO_NORMALIZE=1

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/tensorflow-model-optimization/"

LICENSE=""
SLOT="0"
KEYWORDS="amd64 arm64"

REQUIRES_DIST="
	absl-py ~=1.2
	dm-tree ~=0.1.1
	enum34 ~=1.1 ; python_version < '3.4'
	numpy ~=1.23
	six ~=1.14
"
GENERATED_RDEPEND="${RDEPEND}
	>=dev-python/absl-py-1.2[${PYTHON_USEDEP}] =dev-python/absl-py-1*[${PYTHON_USEDEP}]
	>=dev-python/dm-tree-0.1.1[${PYTHON_USEDEP}] =dev-python/dm-tree-0.1*[${PYTHON_USEDEP}]
	>=dev-python/numpy-1.23[${PYTHON_USEDEP}] =dev-python/numpy-1*[${PYTHON_USEDEP}]
	>=dev-python/six-1.14[${PYTHON_USEDEP}] =dev-python/six-1*[${PYTHON_USEDEP}]
"
RDEPEND="${GENERATED_RDEPEND}"

distutils_enable_tests pytest
