# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
GENERATED_IUSE="pytest"
IUSE="${GENERATED_IUSE}"

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/fabric/"

LICENSE="BSD"
SLOT="0"
KEYWORDS="amd64 arm64"

REQUIRES_DIST="
	decorator >=5
	deprecated >=1.2
	invoke >=2.0
	paramiko >=2.4
	pytest >=7 ; extra == 'pytest'
"
GENERATED_RDEPEND="${RDEPEND}
	>=dev-python/decorator-5[${PYTHON_USEDEP}]
	>=dev-python/deprecated-1.2[${PYTHON_USEDEP}]
	>=dev-python/invoke-2.0[${PYTHON_USEDEP}]
	>=dev-python/paramiko-2.4[${PYTHON_USEDEP}]
	pytest? ( >=dev-python/pytest-7[${PYTHON_USEDEP}] )
"
RDEPEND="${GENERATED_RDEPEND}"

distutils_enable_tests pytest
