# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
GENERATED_IUSE="all test"
IUSE="${GENERATED_IUSE}"

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/flox/"

LICENSE=""
SLOT="0"
KEYWORDS="amd64 arm64"

REQUIRES_DIST="
	cachey; extra == 'all'
	dask; extra == 'all'
	netCDF4; extra == 'test'
	numba; extra == 'all'
	numbagg; extra == 'all'
	numpy>=1.22
	numpy_groupies>=0.9.19
	packaging>=21.3
	pandas>=1.5
	scipy>=1.9
	toolz
	xarray; extra == 'all'
"
GENERATED_RDEPEND="${RDEPEND}
	all? ( dev-python/cachey[${PYTHON_USEDEP}] )
	all? ( dev-python/dask[${PYTHON_USEDEP}] )
	all? ( dev-python/numba[${PYTHON_USEDEP}] )
	all? ( dev-python/numbagg[${PYTHON_USEDEP}] )
	>=dev-python/numpy-1.22[${PYTHON_USEDEP}]
	>=dev-python/numpy-groupies-0.9.19[${PYTHON_USEDEP}]
	>=dev-python/packaging-21.3[${PYTHON_USEDEP}]
	>=dev-python/pandas-1.5[${PYTHON_USEDEP}]
	>=dev-python/scipy-1.9[${PYTHON_USEDEP}]
	dev-python/toolz[${PYTHON_USEDEP}]
	all? ( dev-python/xarray[${PYTHON_USEDEP}] )
"
RDEPEND="${GENERATED_RDEPEND}"

distutils_enable_tests pytest
GENERATED_BDEPEND="${BDEPEND}
	test? (
		dev-python/netcdf4[${PYTHON_USEDEP}]
	)
"
BDEPEND="${GENERATED_BDEPEND}"
