# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
IUSE=""

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/aws-cdk-lib/"

LICENSE="Apache-2.0"
SLOT="0"
KEYWORDS="amd64 arm64"

GENERATED_DEPEND="${RDEPEND}
	<dev-python/aws-cdk-asset-awscli-v1-3.0.0[${PYTHON_USEDEP}]
	<dev-python/aws-cdk-asset-kubectl-v20-3.0.0[${PYTHON_USEDEP}]
	<dev-python/aws-cdk-asset-node-proxy-agent-v6-3.0.0[${PYTHON_USEDEP}]
	<dev-python/aws-cdk-cloud-assembly-schema-40.0.0[${PYTHON_USEDEP}]
	<dev-python/constructs-11.0.0[${PYTHON_USEDEP}]
	<dev-python/jsii-2.0.0[${PYTHON_USEDEP}]
	>=dev-python/publication-0.0.3[${PYTHON_USEDEP}]
	<dev-python/typeguard-4.3.0[${PYTHON_USEDEP}]
"
RDEPEND="${GENERATED_DEPEND}"

distutils_enable_tests pytest
