# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
GENERATED_IUSE="toml yaml"
IUSE="${GENERATED_IUSE}"

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/simple-parsing/"

LICENSE="MIT"
SLOT="0"
KEYWORDS="amd64 arm64"

REQUIRES_DIST="
	docstring-parser<1.0,>=0.15
	pyyaml<7.0.0,>=6.0.1; extra == 'yaml'
	tomli-w<2.0.0,>=1.0.0; extra == 'toml'
	tomli<3.0.0,>=2.0.1; extra == 'toml'
	typing-extensions>=4.5.0
"
GENERATED_RDEPEND="${RDEPEND}
	>=dev-python/docstring-parser-0.15[${PYTHON_USEDEP}] <dev-python/docstring-parser-1.0[${PYTHON_USEDEP}]
	yaml? ( >=dev-python/pyyaml-6.0.1[${PYTHON_USEDEP}] <dev-python/pyyaml-7.0.0[${PYTHON_USEDEP}] )
	toml? ( >=dev-python/tomli-2.0.1[${PYTHON_USEDEP}] <dev-python/tomli-3.0.0[${PYTHON_USEDEP}] )
	toml? ( >=dev-python/tomli-w-1.0.0[${PYTHON_USEDEP}] <dev-python/tomli-w-2.0.0[${PYTHON_USEDEP}] )
	>=dev-python/typing-extensions-4.5.0[${PYTHON_USEDEP}]
"
RDEPEND="${GENERATED_RDEPEND}"

distutils_enable_tests pytest
