# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
GENERATED_IUSE="doc test"
IUSE="${GENERATED_IUSE}"

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/hdf5plugin/"

LICENSE=""
SLOT="0"
KEYWORDS="amd64 arm64"

REQUIRES_DIST="
	blosc2-grok>=0.2.2; python_version >= '3.9' and extra == 'test'
	blosc2>=2.5.1; python_version >= '3.9' and extra == 'test'
	h5py>=3.0.0
	ipython; extra == 'doc'
	nbsphinx; extra == 'doc'
	sphinx-rtd-theme; extra == 'doc'
	sphinx; extra == 'doc'
"
GENERATED_RDEPEND="${RDEPEND}
	>=dev-python/h5py-3.0.0[${PYTHON_USEDEP}]
	doc? ( dev-python/ipython[${PYTHON_USEDEP}] )
	doc? ( dev-python/nbsphinx[${PYTHON_USEDEP}] )
	doc? ( dev-python/sphinx[${PYTHON_USEDEP}] )
	doc? ( dev-python/sphinx-rtd-theme[${PYTHON_USEDEP}] )
"
RDEPEND="${GENERATED_RDEPEND}"

distutils_enable_tests pytest
GENERATED_BDEPEND="${BDEPEND}
	test? (
		>=dev-python/blosc2-2.5.1[${PYTHON_USEDEP}]
		>=dev-python/blosc2-grok-0.2.2[${PYTHON_USEDEP}]
	)
"
BDEPEND="${GENERATED_BDEPEND}"
