# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
IUSE=""

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/graphene/"

LICENSE="MIT"
SLOT="0"
KEYWORDS="amd64 arm64"

GENERATED_DEPEND="${RDEPEND}
	<dev-python/graphql-core-3.3[${PYTHON_USEDEP}]
	<dev-python/graphql-relay-3.3[${PYTHON_USEDEP}]
	<dev-python/python-dateutil-3[${PYTHON_USEDEP}]
	<dev-python/typing-extensions-5[${PYTHON_USEDEP}]
"
RDEPEND="${GENERATED_DEPEND}"

distutils_enable_tests pytest
BDEPEND+=" test? (
	<dev-python/coveralls-5[${PYTHON_USEDEP}]
	<dev-python/mypy-2[${PYTHON_USEDEP}]
	<dev-python/pytest-9[${PYTHON_USEDEP}]
	<dev-python/pytest-asyncio-2[${PYTHON_USEDEP}]
	<dev-python/pytest-benchmark-5[${PYTHON_USEDEP}]
	<dev-python/pytest-cov-6[${PYTHON_USEDEP}]
	<dev-python/pytest-mock-4[${PYTHON_USEDEP}]
	~dev-python/ruff-0.5.0[${PYTHON_USEDEP}]
	<dev-python/types-python-dateutil-3[${PYTHON_USEDEP}]
)"
