# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
GENERATED_IUSE="lint"
IUSE="${GENERATED_IUSE}"

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/kedro-telemetry/"

LICENSE=""
SLOT="0"
KEYWORDS="amd64 arm64"

GENERATED_RDEPEND="${RDEPEND}
	>=dev-python/appdirs-1.4.4[${PYTHON_USEDEP}]
	lint? ( <dev-python/bandit-2.0[${PYTHON_USEDEP}] )
	lint? ( >=dev-python/black-22.0[${PYTHON_USEDEP}] =dev-python/black-22*[${PYTHON_USEDEP}] )
	>=dev-python/kedro-0.18.0[${PYTHON_USEDEP}]
	lint? ( >=dev-python/mypy-1.0[${PYTHON_USEDEP}] =dev-python/mypy-1*[${PYTHON_USEDEP}] )
	>=dev-python/requests-2.20[${PYTHON_USEDEP}] =dev-python/requests-2*[${PYTHON_USEDEP}]
	lint? ( >=dev-python/ruff-0.0.290[${PYTHON_USEDEP}] =dev-python/ruff-0.0*[${PYTHON_USEDEP}] )
	lint? ( <dev-python/trufflehog-3.0[${PYTHON_USEDEP}] )
	lint? ( dev-python/types-pyyaml[${PYTHON_USEDEP}] )
	lint? ( dev-python/types-requests[${PYTHON_USEDEP}] )
	lint? ( dev-python/types-toml[${PYTHON_USEDEP}] )
	lint? ( >=dev-vcs/pre-commit-2.9.2[${PYTHON_USEDEP}] )
"
RDEPEND="${GENERATED_RDEPEND}"

distutils_enable_tests pytest
GENERATED_BDEPEND="${BDEPEND}
	test? (
		dev-python/pytest[${PYTHON_USEDEP}]
		dev-python/pytest-cov[${PYTHON_USEDEP}]
		dev-python/pytest-mock[${PYTHON_USEDEP}]
		>=dev-python/pytest-xdist-2.2.1[psutil,${PYTHON_USEDEP}] =dev-python/pytest-xdist-2.2*[psutil,${PYTHON_USEDEP}]
		=dev-python/pyyaml-5.3.1[${PYTHON_USEDEP}]
		dev-python/wheel[${PYTHON_USEDEP}]
	)
"
BDEPEND="${GENERATED_BDEPEND}"
