# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
GENERATED_IUSE="all polars"
IUSE="${GENERATED_IUSE}"

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/bigframes/"

LICENSE=""
SLOT="0"
KEYWORDS="amd64 arm64"

GENERATED_RDEPEND="${RDEPEND}
	<dev-python/atpublic-6[${PYTHON_USEDEP}]
	>=dev-python/cloudpickle-2.0.0[${PYTHON_USEDEP}]
	>=dev-python/db-dtypes-1.4.0[${PYTHON_USEDEP}]
	>=dev-python/fsspec-2023.3.0[${PYTHON_USEDEP}]
	>=dev-python/gcsfs-2023.3.0[${PYTHON_USEDEP}]
	>=dev-python/geopandas-0.12.2[${PYTHON_USEDEP}]
	<dev-python/google-auth-3.0_pre[${PYTHON_USEDEP}]
	>=dev-python/google-cloud-bigquery-3.18.0[bqstorage,pandas,${PYTHON_USEDEP}]
	>=dev-python/google-cloud-bigquery-connection-1.12.0[${PYTHON_USEDEP}]
	>=dev-python/google-cloud-bigtable-2.24.0[${PYTHON_USEDEP}]
	>=dev-python/google-cloud-functions-1.12.0[${PYTHON_USEDEP}]
	>=dev-python/google-cloud-iam-2.12.1[${PYTHON_USEDEP}]
	>=dev-python/google-cloud-pubsub-2.21.4[${PYTHON_USEDEP}]
	>=dev-python/google-cloud-resource-manager-1.10.3[${PYTHON_USEDEP}]
	>=dev-python/google-cloud-storage-2.0.0[${PYTHON_USEDEP}]
	all? ( dev-python/google-cloud-testutils[${PYTHON_USEDEP}] )
	>=dev-python/humanize-4.6.0[${PYTHON_USEDEP}]
	>=dev-python/ipywidgets-7.7.1[${PYTHON_USEDEP}]
	<dev-python/jellyfish-1.1.2[${PYTHON_USEDEP}]
	>=dev-python/matplotlib-3.7.1[${PYTHON_USEDEP}]
	all? ( dev-python/nox[${PYTHON_USEDEP}] )
	>=dev-python/numpy-1.24.0[${PYTHON_USEDEP}]
	>=dev-python/pandas-1.5.3[${PYTHON_USEDEP}]
	>=dev-python/pandas-gbq-0.26.0[${PYTHON_USEDEP}]
	<dev-python/parsy-3[${PYTHON_USEDEP}]
	all? ( >=dev-python/polars-1.7.0[${PYTHON_USEDEP}] )
	polars? ( >=dev-python/polars-1.7.0[${PYTHON_USEDEP}] )
	>=dev-python/pyarrow-10.0.1[${PYTHON_USEDEP}]
	>=dev-python/pydata-google-auth-1.8.2[${PYTHON_USEDEP}]
	all? ( dev-python/pytest[${PYTHON_USEDEP}] )
	all? ( dev-python/pytest-mock[${PYTHON_USEDEP}] )
	<dev-python/python-dateutil-3[${PYTHON_USEDEP}]
	>=dev-python/pytz-2022.7[${PYTHON_USEDEP}]
	>=dev-python/requests-2.27.1[${PYTHON_USEDEP}]
	<dev-python/rich-14[${PYTHON_USEDEP}]
	>=dev-python/scikit-learn-1.2.2[${PYTHON_USEDEP}]
	<dev-python/sqlalchemy-3.0_pre[${PYTHON_USEDEP}]
	>=dev-python/sqlglot-23.6.3[${PYTHON_USEDEP}]
	>=dev-python/tabulate-0.9[${PYTHON_USEDEP}]
	<dev-python/toolz-2[${PYTHON_USEDEP}]
	<dev-python/typing-extensions-5[${PYTHON_USEDEP}]
	all? ( dev-vcs/pre-commit[${PYTHON_USEDEP}] )
"
RDEPEND="${GENERATED_RDEPEND}"

distutils_enable_tests pytest
GENERATED_BDEPEND="${BDEPEND}
	test? (
		dev-python/google-cloud-testutils[${PYTHON_USEDEP}]
		dev-python/nox[${PYTHON_USEDEP}]
		dev-python/pytest[${PYTHON_USEDEP}]
		dev-python/pytest-mock[${PYTHON_USEDEP}]
		dev-vcs/pre-commit[${PYTHON_USEDEP}]
	)
"
BDEPEND="${GENERATED_BDEPEND}"
