# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
GENERATED_IUSE="all fastai huggingface image lgbm lightning markdown mmcv optuna plots sklearn test tf xgb"
IUSE="${GENERATED_IUSE}"

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/dvclive/"

LICENSE=""
SLOT="0"
KEYWORDS="amd64 arm64"

REQUIRES_DIST="
	datasets; extra == 'huggingface'
	dpath; extra == 'tests'
	dvc-render<2,>=1.0.0
	dvc-studio-client<1,>=0.20
	dvc>=3.48.4
	dvclive[all,tests]; extra == 'dev'
	dvclive[fastai,huggingface,image,lgbm,lightning,markdown,mmcv,optuna,plots,tf,xgb]; extra == 'all'
	dvclive[image,markdown,plots]; extra == 'tests'
	fastai; extra == 'fastai'
	funcy
	gto
	ipython; extra == 'tests'
	jsonargparse[signatures]>=4.26.1; extra == 'lightning'
	lightgbm; extra == 'lgbm'
	lightning>=2.0; extra == 'lightning'
	matplotlib; extra == 'markdown'
	mmcv; extra == 'mmcv'
	mypy==1.14.1; extra == 'dev'
	numpy; extra == 'image'
	numpy; extra == 'plots'
	optuna; extra == 'optuna'
	pandas; extra == 'plots'
	pillow; extra == 'image'
	psutil
	pynvml
	pytest-cov<7.0,>=3.0.0; extra == 'tests'
	pytest-mock<4.0,>=3.8.2; extra == 'tests'
	pytest-sugar<2.0,>=0.9.6; extra == 'tests'
	pytest<9.0,>=7.2.0; extra == 'tests'
	pytest_voluptuous; extra == 'tests'
	ruamel.yaml
	scikit-learn; extra == 'plots'
	scikit-learn; extra == 'sklearn'
	scmrepo<4,>=3
	tensorflow; extra == 'tf'
	tf-keras; extra == 'tests'
	torch; extra == 'lightning'
	transformers; extra == 'huggingface'
	transformers[torch]; extra == 'tests'
	types-PyYAML; extra == 'dev'
	xgboost; extra == 'xgb'
"
GENERATED_RDEPEND="${RDEPEND}
	huggingface? ( dev-python/datasets[${PYTHON_USEDEP}] )
	>=dev-python/dvc-3.48.4[${PYTHON_USEDEP}]
	>=dev-python/dvc-render-1.0.0[${PYTHON_USEDEP}] <dev-python/dvc-render-2[${PYTHON_USEDEP}]
	>=dev-python/dvc-studio-client-0.20[${PYTHON_USEDEP}] <dev-python/dvc-studio-client-1[${PYTHON_USEDEP}]
	all? ( dev-python/dvclive[fastai,huggingface,image,lgbm,lightning,markdown,mmcv,optuna,plots,tf,xgb,${PYTHON_USEDEP}] )
	fastai? ( dev-python/fastai[${PYTHON_USEDEP}] )
	dev-python/funcy[${PYTHON_USEDEP}]
	dev-python/gto[${PYTHON_USEDEP}]
	lightning? ( >=dev-python/jsonargparse-4.26.1[signatures,${PYTHON_USEDEP}] )
	lgbm? ( dev-python/lightgbm[${PYTHON_USEDEP}] )
	lightning? ( >=dev-python/lightning-2.0[${PYTHON_USEDEP}] )
	markdown? ( dev-python/matplotlib[${PYTHON_USEDEP}] )
	mmcv? ( dev-python/mmcv[${PYTHON_USEDEP}] )
	image? ( dev-python/numpy[${PYTHON_USEDEP}] )
	plots? ( dev-python/numpy[${PYTHON_USEDEP}] )
	optuna? ( dev-python/optuna[${PYTHON_USEDEP}] )
	plots? ( dev-python/pandas[${PYTHON_USEDEP}] )
	image? ( dev-python/pillow[${PYTHON_USEDEP}] )
	dev-python/psutil[${PYTHON_USEDEP}]
	dev-python/pynvml[${PYTHON_USEDEP}]
	dev-python/ruamel-yaml[${PYTHON_USEDEP}]
	plots? ( dev-python/scikit-learn[${PYTHON_USEDEP}] )
	sklearn? ( dev-python/scikit-learn[${PYTHON_USEDEP}] )
	>=dev-python/scmrepo-3[${PYTHON_USEDEP}] <dev-python/scmrepo-4[${PYTHON_USEDEP}]
	tf? ( dev-python/tensorflow[${PYTHON_USEDEP}] )
	lightning? ( dev-python/torch[${PYTHON_USEDEP}] )
	huggingface? ( dev-python/transformers[${PYTHON_USEDEP}] )
	xgb? ( dev-python/xgboost[${PYTHON_USEDEP}] )
"
RDEPEND="${GENERATED_RDEPEND}"

distutils_enable_tests pytest
GENERATED_BDEPEND="${BDEPEND}
	test? (
		dev-python/dpath[${PYTHON_USEDEP}]
		dev-python/dvclive[all,tests,${PYTHON_USEDEP}]
		dev-python/dvclive[image,markdown,plots,${PYTHON_USEDEP}]
		dev-python/ipython[${PYTHON_USEDEP}]
		~dev-python/mypy-1.14.1[${PYTHON_USEDEP}]
		>=dev-python/pytest-7.2.0[${PYTHON_USEDEP}] <dev-python/pytest-9.0[${PYTHON_USEDEP}]
		>=dev-python/pytest-cov-3.0.0[${PYTHON_USEDEP}] <dev-python/pytest-cov-7.0[${PYTHON_USEDEP}]
		>=dev-python/pytest-mock-3.8.2[${PYTHON_USEDEP}] <dev-python/pytest-mock-4.0[${PYTHON_USEDEP}]
		>=dev-python/pytest-sugar-0.9.6[${PYTHON_USEDEP}] <dev-python/pytest-sugar-2.0[${PYTHON_USEDEP}]
		dev-python/pytest-voluptuous[${PYTHON_USEDEP}]
		dev-python/tf-keras[${PYTHON_USEDEP}]
		dev-python/transformers[torch,${PYTHON_USEDEP}]
		dev-python/types-pyyaml[${PYTHON_USEDEP}]
	)
"
BDEPEND="${GENERATED_BDEPEND}"
