# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
GENERATED_IUSE="check cover doc enabler type"
IUSE="${GENERATED_IUSE}"

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/jaraco-mongodb/"

LICENSE=""
SLOT="0"
KEYWORDS="amd64 arm64"

REQUIRES_DIST="
	autocommand
	backports.tarfile; python_version < '3.12'
	cachetools
	cherrypy; extra == 'doc'
	cherrypy; extra == 'test'
	furo; extra == 'doc'
	jaraco.collections>=2
	jaraco.context>=2
	jaraco.functools>=2
	jaraco.itertools>=2
	jaraco.logging>=2
	jaraco.packaging>=9.3; extra == 'doc'
	jaraco.services>=2
	jaraco.ui>=2
	more-itertools
	portend
	pymongo>=3.5
	pytest!=8.1.*,>=6; extra == 'test'
	pytest-checkdocs>=2.4; extra == 'check'
	pytest-cov; extra == 'cover'
	pytest-enabler>=2.2; extra == 'enabler'
	pytest-mypy; extra == 'type'
	pytest-ruff>=0.2.1; sys_platform != 'cygwin' and extra == 'check'
	python-dateutil
	pytimeparse
	rst.linker>=1.9; extra == 'doc'
	sphinx-lint; extra == 'doc'
	sphinx>=3.5; extra == 'doc'
	tempora
	types-cachetools; extra == 'type'
	types-python-dateutil; extra == 'type'
"
GENERATED_RDEPEND="${RDEPEND}
	dev-python/autocommand[${PYTHON_USEDEP}]
	dev-python/cachetools[${PYTHON_USEDEP}]
	doc? ( dev-python/cherrypy[${PYTHON_USEDEP}] )
	doc? ( dev-python/furo[${PYTHON_USEDEP}] )
	>=dev-python/jaraco-collections-2[${PYTHON_USEDEP}]
	>=dev-python/jaraco-context-2[${PYTHON_USEDEP}]
	>=dev-python/jaraco-functools-2[${PYTHON_USEDEP}]
	>=dev-python/jaraco-itertools-2[${PYTHON_USEDEP}]
	>=dev-python/jaraco-logging-2[${PYTHON_USEDEP}]
	doc? ( >=dev-python/jaraco-packaging-9.3[${PYTHON_USEDEP}] )
	>=dev-python/jaraco-services-2[${PYTHON_USEDEP}]
	>=dev-python/jaraco-ui-2[${PYTHON_USEDEP}]
	dev-python/more-itertools[${PYTHON_USEDEP}]
	dev-python/portend[${PYTHON_USEDEP}]
	>=dev-python/pymongo-3.5[${PYTHON_USEDEP}]
	check? ( >=dev-python/pytest-checkdocs-2.4[${PYTHON_USEDEP}] )
	cover? ( dev-python/pytest-cov[${PYTHON_USEDEP}] )
	enabler? ( >=dev-python/pytest-enabler-2.2[${PYTHON_USEDEP}] )
	type? ( dev-python/pytest-mypy[${PYTHON_USEDEP}] )
	check? ( >=dev-python/pytest-ruff-0.2.1[${PYTHON_USEDEP}] )
	dev-python/python-dateutil[${PYTHON_USEDEP}]
	dev-python/pytimeparse[${PYTHON_USEDEP}]
	doc? ( >=dev-python/rst-linker-1.9[${PYTHON_USEDEP}] )
	doc? ( >=dev-python/sphinx-3.5[${PYTHON_USEDEP}] )
	doc? ( dev-python/sphinx-lint[${PYTHON_USEDEP}] )
	dev-python/tempora[${PYTHON_USEDEP}]
	type? ( dev-python/types-cachetools[${PYTHON_USEDEP}] )
	type? ( dev-python/types-python-dateutil[${PYTHON_USEDEP}] )
"
RDEPEND="${GENERATED_RDEPEND}"

distutils_enable_tests pytest
GENERATED_BDEPEND="${BDEPEND}
	test? (
		dev-python/cherrypy[${PYTHON_USEDEP}]
		>=dev-python/pytest-6[${PYTHON_USEDEP}] !=dev-python/pytest-8.1*[${PYTHON_USEDEP}]
	)
"
BDEPEND="${GENERATED_BDEPEND}"
