# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
PYPI_NO_NORMALIZE=1
GENERATED_IUSE="docs test zcml"
IUSE="${GENERATED_IUSE}"

PYPI_PN="zope.i18n"
inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/zope.i18n/"

LICENSE=""
SLOT="0"
KEYWORDS="amd64 arm64"

GENERATED_DEPEND="
	dev-python/python-gettext[${PYTHON_USEDEP}]
	dev-python/pytz[${PYTHON_USEDEP}]
	docs? ( dev-python/repoze-sphinx-autointerface[${PYTHON_USEDEP}] )
	dev-python/setuptools[${PYTHON_USEDEP}]
	docs? ( dev-python/sphinx[${PYTHON_USEDEP}] )
	dev-python/zope-component[${PYTHON_USEDEP}]
	test? ( dev-python/zope-component[zcml,${PYTHON_USEDEP}] )
	zcml? ( dev-python/zope-component[zcml,${PYTHON_USEDEP}] )
	test? ( dev-python/zope-configuration[${PYTHON_USEDEP}] )
	zcml? ( dev-python/zope-configuration[${PYTHON_USEDEP}] )
	dev-python/zope-deprecation[${PYTHON_USEDEP}]
	>=dev-python/zope-i18nmessageid-4.3[${PYTHON_USEDEP}]
	test? ( dev-python/zope-publisher[${PYTHON_USEDEP}] )
	dev-python/zope-schema[${PYTHON_USEDEP}]
	test? ( dev-python/zope-security[${PYTHON_USEDEP}] )
	zcml? ( dev-python/zope-security[${PYTHON_USEDEP}] )
	test? ( dev-python/zope-testing[${PYTHON_USEDEP}] )
	test? ( dev-python/zope-testrunner[${PYTHON_USEDEP}] )
"
RDEPEND="${GENERATED_DEPEND}"

distutils_enable_tests pytest