# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
PYPI_NO_NORMALIZE=1
GENERATED_IUSE="dev docs-specific quality test"
IUSE="${GENERATED_IUSE}"

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/peft/"

LICENSE=""
SLOT="0"
KEYWORDS="amd64 arm64"

GENERATED_DEPEND="
	>=dev-python/accelerate-0.21.0[${PYTHON_USEDEP}]
	dev? ( dev-python/black[${PYTHON_USEDEP}] )
	docs-specific? ( dev-python/black[${PYTHON_USEDEP}] )
	quality? ( dev-python/black[${PYTHON_USEDEP}] )
	test? ( dev-python/black[${PYTHON_USEDEP}] )
	test? ( dev-python/datasets[${PYTHON_USEDEP}] )
	test? ( dev-python/diffusers[${PYTHON_USEDEP}] )
	dev? ( dev-python/hf-doc-builder[${PYTHON_USEDEP}] )
	docs-specific? ( dev-python/hf-doc-builder[${PYTHON_USEDEP}] )
	quality? ( dev-python/hf-doc-builder[${PYTHON_USEDEP}] )
	test? ( dev-python/hf-doc-builder[${PYTHON_USEDEP}] )
	>=dev-python/huggingface-hub-0.25.0[${PYTHON_USEDEP}]
	>=dev-python/numpy-1.17[${PYTHON_USEDEP}]
	>=dev-python/packaging-20.0[${PYTHON_USEDEP}]
	test? ( dev-python/parameterized[${PYTHON_USEDEP}] )
	test? ( dev-python/protobuf[${PYTHON_USEDEP}] )
	dev-python/psutil[${PYTHON_USEDEP}]
	test? ( dev-python/pytest[${PYTHON_USEDEP}] )
	test? ( dev-python/pytest-cov[${PYTHON_USEDEP}] )
	test? ( dev-python/pytest-xdist[${PYTHON_USEDEP}] )
	dev-python/pyyaml[${PYTHON_USEDEP}]
	dev? ( ~dev-python/ruff-0.6.1[${PYTHON_USEDEP}] )
	quality? ( ~dev-python/ruff-0.6.1[${PYTHON_USEDEP}] )
	test? ( ~dev-python/ruff-0.6.1[${PYTHON_USEDEP}] )
	dev-python/safetensors[${PYTHON_USEDEP}]
	test? ( dev-python/scipy[${PYTHON_USEDEP}] )
	test? ( dev-python/sentencepiece[${PYTHON_USEDEP}] )
	>=dev-python/torch-1.13.0[${PYTHON_USEDEP}]
	dev-python/tqdm[${PYTHON_USEDEP}]
	dev-python/transformers[${PYTHON_USEDEP}]
"
RDEPEND="${GENERATED_DEPEND}"

distutils_enable_tests pytest