# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
PYPI_NO_NORMALIZE=1
GENERATED_IUSE="dev langchain sentry test"
IUSE="${GENERATED_IUSE}"

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/posthog/"

LICENSE=""
SLOT="0"
KEYWORDS="amd64 arm64"

GENERATED_DEPEND="
	test? ( dev-python/anthropic[${PYTHON_USEDEP}] )
	>=dev-python/backoff-1.10.0[${PYTHON_USEDEP}]
	dev? ( dev-python/black[${PYTHON_USEDEP}] )
	test? ( dev-python/coverage[${PYTHON_USEDEP}] )
	sentry? ( dev-python/django[${PYTHON_USEDEP}] )
	test? ( dev-python/django[${PYTHON_USEDEP}] )
	dev? ( dev-python/flake8[${PYTHON_USEDEP}] )
	test? ( dev-python/flake8[${PYTHON_USEDEP}] )
	dev? ( dev-python/flake8-print[${PYTHON_USEDEP}] )
	test? ( ~dev-python/freezegun-0.3.15[${PYTHON_USEDEP}] )
	dev? ( dev-python/isort[${PYTHON_USEDEP}] )
	langchain? ( >=dev-python/langchain-0.2.0[${PYTHON_USEDEP}] )
	test? ( >=dev-python/langchain-anthropic-0.2.0[${PYTHON_USEDEP}] )
	test? ( >=dev-python/langchain-community-0.2.0[${PYTHON_USEDEP}] )
	test? ( >=dev-python/langchain-openai-0.2.0[${PYTHON_USEDEP}] )
	test? ( dev-python/langgraph[${PYTHON_USEDEP}] )
	test? ( >=dev-python/mock-2.0.0[${PYTHON_USEDEP}] )
	>=dev-python/monotonic-1.5[${PYTHON_USEDEP}]
	test? ( dev-python/openai[${PYTHON_USEDEP}] )
	test? ( dev-python/pylint[${PYTHON_USEDEP}] )
	test? ( dev-python/pytest[${PYTHON_USEDEP}] )
	test? ( dev-python/pytest-asyncio[${PYTHON_USEDEP}] )
	test? ( dev-python/pytest-timeout[${PYTHON_USEDEP}] )
	>dev-python/python-dateutil-2.1[${PYTHON_USEDEP}]
	<dev-python/requests-3.0[${PYTHON_USEDEP}]
	sentry? ( dev-python/sentry-sdk[${PYTHON_USEDEP}] )
	>=dev-python/six-1.5[${PYTHON_USEDEP}]
	dev? ( dev-vcs/pre-commit[${PYTHON_USEDEP}] )
"
RDEPEND="${GENERATED_DEPEND}"

distutils_enable_tests pytest