# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
GENERATED_IUSE="abbreviation attacut benchmarks coreference-resolution dependency-parsing el esupar full generate icu ipa ml mt5 nlpo3 onnx oskut sefr-cut spacy-thai spell ssg textaugment thai-nner thai2fit thai2rom transformers-ud translate wangchanberta wangchanglm word-approximation wordnet wsd wtp wunsen"
IUSE="${GENERATED_IUSE}"

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/pythainlp/"

LICENSE=""
SLOT="0"
KEYWORDS="amd64 arm64"

GENERATED_DEPEND="${RDEPEND}
	attacut? ( >=dev-python/attacut-1.0.6[${PYTHON_USEDEP}] )
	full? ( >=dev-python/attacut-1.0.4[${PYTHON_USEDEP}] )
	dev-python/backports-zoneinfo[${PYTHON_USEDEP}]
	full? ( >=dev-python/bpemb-0.3.2[${PYTHON_USEDEP}] )
	textaugment? ( dev-python/bpemb[${PYTHON_USEDEP}] )
	full? ( >=dev-python/emoji-0.5.1[${PYTHON_USEDEP}] )
	thai2fit? ( >=dev-python/emoji-0.5.1[${PYTHON_USEDEP}] )
	full? ( >=dev-python/epitran-1.1[${PYTHON_USEDEP}] )
	ipa? ( >=dev-python/epitran-1.1[${PYTHON_USEDEP}] )
	esupar? ( >=dev-python/esupar-1.3.8[${PYTHON_USEDEP}] )
	full? ( >=dev-python/fairseq-0.10.0[${PYTHON_USEDEP}] )
	translate? ( >=dev-python/fairseq-0.10.0[${PYTHON_USEDEP}] )
	full? ( <dev-python/fastai-2.0[${PYTHON_USEDEP}] )
	generate? ( <dev-python/fastai-2.0[${PYTHON_USEDEP}] )
	coreference-resolution? ( >=dev-python/fastcoref-2.1.5[${PYTHON_USEDEP}] )
	full? ( >=dev-python/fastcoref-2.1.5[${PYTHON_USEDEP}] )
	full? ( >=dev-python/gensim-4.0.0[${PYTHON_USEDEP}] )
	textaugment? ( >=dev-python/gensim-4.0.0[${PYTHON_USEDEP}] )
	thai2fit? ( >=dev-python/gensim-4.0.0[${PYTHON_USEDEP}] )
	abbreviation? ( >=dev-python/khamyo-0.2.0[${PYTHON_USEDEP}] )
	full? ( >=dev-python/khamyo-0.2.0[${PYTHON_USEDEP}] )
	el? ( >=dev-python/multiel-0.5[${PYTHON_USEDEP}] )
	full? ( >=dev-python/nlpo3-1.2.2[${PYTHON_USEDEP}] )
	nlpo3? ( >=dev-python/nlpo3-1.2.2[${PYTHON_USEDEP}] )
	full? ( >=dev-python/nltk-3.3[${PYTHON_USEDEP}] )
	wordnet? ( >=dev-python/nltk-3.3[${PYTHON_USEDEP}] )
	benchmarks? ( >=dev-python/numpy-1.22[${PYTHON_USEDEP}] )
	esupar? ( dev-python/numpy[${PYTHON_USEDEP}] )
	full? ( >=dev-python/numpy-1.22[${PYTHON_USEDEP}] )
	ml? ( >=dev-python/numpy-1.22[${PYTHON_USEDEP}] )
	onnx? ( >=dev-python/numpy-1.22[${PYTHON_USEDEP}] )
	thai2fit? ( >=dev-python/numpy-1.22[${PYTHON_USEDEP}] )
	thai2rom? ( >=dev-python/numpy-1.22[${PYTHON_USEDEP}] )
	full? ( >=dev-python/onnxruntime-1.10.0[${PYTHON_USEDEP}] )
	onnx? ( >=dev-python/onnxruntime-1.10.0[${PYTHON_USEDEP}] )
	full? ( >=dev-python/oskut-1.3[${PYTHON_USEDEP}] )
	oskut? ( >=dev-python/oskut-1.3[${PYTHON_USEDEP}] )
	benchmarks? ( >=dev-python/pandas-0.24[${PYTHON_USEDEP}] )
	full? ( >=dev-python/pandas-0.24[${PYTHON_USEDEP}] )
	wangchanglm? ( >=dev-python/pandas-0.24[${PYTHON_USEDEP}] )
	full? ( >=dev-python/panphon-0.20.0[${PYTHON_USEDEP}] )
	word-approximation? ( >=dev-python/panphon-0.20.0[${PYTHON_USEDEP}] )
	full? ( >=dev-python/phunspell-0.1.6[${PYTHON_USEDEP}] )
	spell? ( >=dev-python/phunspell-0.1.6[${PYTHON_USEDEP}] )
	full? ( >=dev-python/pyicu-2.3[${PYTHON_USEDEP}] )
	icu? ( >=dev-python/pyicu-2.3[${PYTHON_USEDEP}] )
	benchmarks? ( >=dev-python/pyyaml-5.3.1[${PYTHON_USEDEP}] )
	full? ( >=dev-python/pyyaml-5.3.1[${PYTHON_USEDEP}] )
	>=dev-python/requests-2.22.0[${PYTHON_USEDEP}]
	full? ( >=dev-python/sacremoses-0.0.41[${PYTHON_USEDEP}] )
	translate? ( >=dev-python/sacremoses-0.0.41[${PYTHON_USEDEP}] )
	full? ( >=dev-python/sefr-cut-1.1[${PYTHON_USEDEP}] )
	sefr-cut? ( >=dev-python/sefr-cut-1.1[${PYTHON_USEDEP}] )
	full? ( >=dev-python/sentence-transformers-2.2.2[${PYTHON_USEDEP}] )
	wsd? ( >=dev-python/sentence-transformers-2.2.2[${PYTHON_USEDEP}] )
	full? ( >=dev-python/sentencepiece-0.1.91[${PYTHON_USEDEP}] )
	mt5? ( >=dev-python/sentencepiece-0.1.91[${PYTHON_USEDEP}] )
	onnx? ( >=dev-python/sentencepiece-0.1.91[${PYTHON_USEDEP}] )
	translate? ( >=dev-python/sentencepiece-0.1.91[${PYTHON_USEDEP}] )
	wangchanberta? ( >=dev-python/sentencepiece-0.1.91[${PYTHON_USEDEP}] )
	wangchanglm? ( >=dev-python/sentencepiece-0.1.91[${PYTHON_USEDEP}] )
	coreference-resolution? ( >=dev-python/spacy-3.0[${PYTHON_USEDEP}] )
	full? ( >=dev-python/spacy-3.0[${PYTHON_USEDEP}] )
	dependency-parsing? ( >=dev-python/spacy-thai-0.7.1[${PYTHON_USEDEP}] )
	full? ( >=dev-python/spacy-thai-0.7.1[${PYTHON_USEDEP}] )
	spacy-thai? ( >=dev-python/spacy-thai-0.7.1[${PYTHON_USEDEP}] )
	full? ( >=dev-python/spylls-0.1.5[${PYTHON_USEDEP}] )
	spell? ( >=dev-python/spylls-0.1.5[${PYTHON_USEDEP}] )
	full? ( >=dev-python/ssg-0.0.8[${PYTHON_USEDEP}] )
	ssg? ( >=dev-python/ssg-0.0.8[${PYTHON_USEDEP}] )
	full? ( >=dev-python/symspellpy-6.7.6[${PYTHON_USEDEP}] )
	spell? ( >=dev-python/symspellpy-6.7.6[${PYTHON_USEDEP}] )
	full? ( dev-python/thai-nner[${PYTHON_USEDEP}] )
	thai-nner? ( dev-python/thai-nner[${PYTHON_USEDEP}] )
	full? ( >=dev-python/torch-1.0.0[${PYTHON_USEDEP}] )
	ml? ( >=dev-python/torch-1.0.0[${PYTHON_USEDEP}] )
	thai2rom? ( >=dev-python/torch-1.0.0[${PYTHON_USEDEP}] )
	translate? ( >=dev-python/torch-1.0.0[${PYTHON_USEDEP}] )
	dependency-parsing? ( >=dev-python/transformers-4.22.1[${PYTHON_USEDEP}] )
	esupar? ( >=dev-python/transformers-4.22.1[${PYTHON_USEDEP}] )
	full? ( >=dev-python/transformers-4.22.1[${PYTHON_USEDEP}] )
	mt5? ( >=dev-python/transformers-4.6.0[${PYTHON_USEDEP}] )
	transformers-ud? ( >=dev-python/transformers-4.22.1[${PYTHON_USEDEP}] )
	translate? ( >=dev-python/transformers-4.6.0[${PYTHON_USEDEP}] )
	wangchanberta? ( >=dev-python/transformers-4.6.0[${PYTHON_USEDEP}] )
	wangchanglm? ( >=dev-python/transformers-4.6.0[${PYTHON_USEDEP}] )
	wtp? ( >=dev-python/transformers-4.6.0[${PYTHON_USEDEP}] )
	dependency-parsing? ( >=dev-python/ufal-chu-liu-edmonds-1.0.2[${PYTHON_USEDEP}] )
	full? ( >=dev-python/ufal-chu-liu-edmonds-1.0.2[${PYTHON_USEDEP}] )
	transformers-ud? ( >=dev-python/ufal-chu-liu-edmonds-1.0.2[${PYTHON_USEDEP}] )
	full? ( >=dev-python/wtpsplit-1.0.1[${PYTHON_USEDEP}] )
	wtp? ( >=dev-python/wtpsplit-1.0.1[${PYTHON_USEDEP}] )
	full? ( >=dev-python/wunsen-0.0.3[${PYTHON_USEDEP}] )
	wunsen? ( >=dev-python/wunsen-0.0.1[${PYTHON_USEDEP}] )
"
RDEPEND="${GENERATED_DEPEND}"

distutils_enable_tests pytest
