# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
GENERATED_IUSE="completion hook-testing"
IUSE="${GENERATED_IUSE}"

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/pyinstaller/"

LICENSE=""
SLOT="0"
KEYWORDS="amd64 arm64"

GENERATED_RDEPEND="${RDEPEND}
	dev-python/altgraph[${PYTHON_USEDEP}]
	completion? ( dev-python/argcomplete[${PYTHON_USEDEP}] )
	hook-testing? ( >=dev-python/execnet-1.5.0[${PYTHON_USEDEP}] )
	>=dev-python/packaging-22.0[${PYTHON_USEDEP}]
	hook-testing? ( dev-python/psutil[${PYTHON_USEDEP}] )
	>=dev-python/pyinstaller-hooks-contrib-2024.9[${PYTHON_USEDEP}]
	hook-testing? ( >=dev-python/pytest-2.7.3[${PYTHON_USEDEP}] )
	>=dev-python/setuptools-42.0.0[${PYTHON_USEDEP}]
"
RDEPEND="${GENERATED_RDEPEND}"

distutils_enable_tests pytest
