# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
IUSE=""

inherit distutils-r1 pypi
SRC_URI="$(pypi_sdist_url ${PN} 1.0.8.post1)"
S="${WORKDIR}/${PN}-1.0.8.post1"

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/usort/"

LICENSE="MIT"
SLOT="0"
KEYWORDS="amd64 arm64"

GENERATED_RDEPEND="${RDEPEND}
	>=dev-python/attrs-21.2.0[${PYTHON_USEDEP}]
	>=dev-python/click-7.0.0[${PYTHON_USEDEP}]
	>=dev-python/libcst-0.3.7[${PYTHON_USEDEP}]
	>=dev-python/moreorless-0.3.0[${PYTHON_USEDEP}]
	>=dev-python/stdlibs-2021.4.1[${PYTHON_USEDEP}]
	>=dev-python/toml-0.10.0[${PYTHON_USEDEP}]
	>=dev-python/trailrunner-1.0[${PYTHON_USEDEP}]
"
RDEPEND="${GENERATED_RDEPEND}"

distutils_enable_tests pytest
