# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
PYPI_NO_NORMALIZE=1
GENERATED_IUSE="aiohttp asgi carbon cron dns grpc raven rich uvicorn uvloop"
IUSE="${GENERATED_IUSE}"

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/aiomisc/"

LICENSE="MIT"
SLOT="0"
KEYWORDS="amd64 arm64"

GENERATED_DEPEND="${PYTHON_DEPS}
	carbon? ( <dev-python/aiocarbon-0.16[${PYTHON_USEDEP}] )
	aiohttp? ( >dev-python/aiohttp-3[${PYTHON_USEDEP}] )
	asgi? ( <dev-python/aiohttp-asgi-0.6.0[${PYTHON_USEDEP}] )
	uvicorn? ( <dev-python/asgiref-4.0[${PYTHON_USEDEP}] )
	<dev-python/colorlog-7.0[${PYTHON_USEDEP}]
	cron? ( ~dev-python/croniter-2.0[${PYTHON_USEDEP}] )
	dns? ( <dev-python/dnslib-0.10[${PYTHON_USEDEP}] )
	grpc? ( <dev-python/grpcio-2.0[${PYTHON_USEDEP}] )
	grpc? ( <dev-python/grpcio-reflection-2.0[${PYTHON_USEDEP}] )
	grpc? ( <dev-python/grpcio-tools-2.0[${PYTHON_USEDEP}] )
	dev-python/logging-journald[${PYTHON_USEDEP}]
	raven? ( dev-python/raven[${PYTHON_USEDEP}] )
	rich? ( dev-python/rich[${PYTHON_USEDEP}] )
	dev-python/setuptools[${PYTHON_USEDEP}]
	uvicorn? ( <dev-python/uvicorn-0.28[${PYTHON_USEDEP}] )
	uvloop? ( <dev-python/uvloop-1[${PYTHON_USEDEP}] )
"
RDEPEND="${GENERATED_DEPEND}"

distutils_enable_tests pytest
