# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
GENERATED_IUSE="aiohttp asgi carbon cron dns grpc raven rich uvicorn uvloop"
IUSE="${GENERATED_IUSE}"

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/aiomisc/"

LICENSE="MIT"
SLOT="0"
KEYWORDS="amd64 arm64"

REQUIRES_DIST="
	aiocarbon<0.16,>=0.15; extra == "carbon"
	aiohttp-asgi<0.6.0,>=0.5.2; extra == "asgi"
	aiohttp>3; extra == "aiohttp" or extra == "raven"
	asgiref<4.0,>=3.7; extra == "uvicorn"
	colorlog<7.0,>=6.0
	croniter==2.0; extra == "cron"
	dnslib<0.10,>=0.9; extra == "dns"
	grpcio-reflection<2.0,>=1.56; extra == "grpc"
	grpcio-tools<2.0,>=1.56; extra == "grpc"
	grpcio<2.0,>=1.56; extra == "grpc"
	logging-journald; sys_platform == "linux"
	raven; extra == "raven"
	rich; extra == "rich"
	setuptools; python_version < "3.8"
	typing_extensions; python_version < "3.10"
	uvicorn<0.28,>=0.27; extra == "uvicorn"
	uvloop<1,>=0.19; extra == "uvloop"
"
GENERATED_RDEPEND="${RDEPEND}
	carbon? ( >=dev-python/aiocarbon-0.15[${PYTHON_USEDEP}] <dev-python/aiocarbon-0.16[${PYTHON_USEDEP}] )
	raven? ( >dev-python/aiohttp-3[${PYTHON_USEDEP}] ) aiohttp? ( >dev-python/aiohttp-3[${PYTHON_USEDEP}] )
	asgi? ( >=dev-python/aiohttp-asgi-0.5.2[${PYTHON_USEDEP}] <dev-python/aiohttp-asgi-0.6.0[${PYTHON_USEDEP}] )
	uvicorn? ( >=dev-python/asgiref-3.7[${PYTHON_USEDEP}] <dev-python/asgiref-4.0[${PYTHON_USEDEP}] )
	>=dev-python/colorlog-6.0[${PYTHON_USEDEP}] <dev-python/colorlog-7.0[${PYTHON_USEDEP}]
	cron? ( ~dev-python/croniter-2.0[${PYTHON_USEDEP}] )
	dns? ( >=dev-python/dnslib-0.9[${PYTHON_USEDEP}] <dev-python/dnslib-0.10[${PYTHON_USEDEP}] )
	grpc? ( >=dev-python/grpcio-1.56[${PYTHON_USEDEP}] <dev-python/grpcio-2.0[${PYTHON_USEDEP}] )
	grpc? ( >=dev-python/grpcio-reflection-1.56[${PYTHON_USEDEP}] <dev-python/grpcio-reflection-2.0[${PYTHON_USEDEP}] )
	grpc? ( >=dev-python/grpcio-tools-1.56[${PYTHON_USEDEP}] <dev-python/grpcio-tools-2.0[${PYTHON_USEDEP}] )
	dev-python/logging-journald[${PYTHON_USEDEP}]
	raven? ( dev-python/raven[${PYTHON_USEDEP}] )
	rich? ( dev-python/rich[${PYTHON_USEDEP}] )
	uvicorn? ( >=dev-python/uvicorn-0.27[${PYTHON_USEDEP}] <dev-python/uvicorn-0.28[${PYTHON_USEDEP}] )
	uvloop? ( >=dev-python/uvloop-0.19[${PYTHON_USEDEP}] <dev-python/uvloop-1[${PYTHON_USEDEP}] )
"
RDEPEND="${GENERATED_RDEPEND}"

distutils_enable_tests pytest
