# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
PYPI_NO_NORMALIZE=1
GENERATED_IUSE="dev docs examples keops pyro test"
IUSE="${GENERATED_IUSE}"

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/gpytorch/"

LICENSE="MIT"
SLOT="0"
KEYWORDS="amd64 arm64"

GENERATED_DEPEND="
	test? ( ~dev-python/flake8-4.0.1[${PYTHON_USEDEP}] )
	test? ( ~dev-python/flake8-print-4.0.0[${PYTHON_USEDEP}] )
	docs? ( <=dev-python/ipykernel-6.17.1[${PYTHON_USEDEP}] )
	docs? ( <=dev-python/ipython-8.6.0[${PYTHON_USEDEP}] )
	examples? ( dev-python/ipython[${PYTHON_USEDEP}] )
	~dev-python/jaxtyping-0.2.19[${PYTHON_USEDEP}]
	examples? ( dev-python/jupyter[${PYTHON_USEDEP}] )
	>=dev-python/linear-operator-0.5.3[${PYTHON_USEDEP}]
	docs? ( dev-python/lxml-html-clean[${PYTHON_USEDEP}] )
	docs? ( <=dev-python/m2r2-0.3.3_p2[${PYTHON_USEDEP}] )
	examples? ( dev-python/matplotlib[${PYTHON_USEDEP}] )
	<=dev-python/mpmath-1.3[${PYTHON_USEDEP}]
	docs? ( <=dev-python/nbclient-0.7.3[${PYTHON_USEDEP}] )
	docs? ( <=dev-python/nbformat-5.8.0[${PYTHON_USEDEP}] )
	docs? ( <=dev-python/nbsphinx-0.9.1[${PYTHON_USEDEP}] )
	test? ( dev-python/nbval[${PYTHON_USEDEP}] )
	docs? ( <=dev-python/platformdirs-3.2.0[${PYTHON_USEDEP}] )
	keops? ( >=dev-python/pykeops-1.1.1[${PYTHON_USEDEP}] )
	pyro? ( >=dev-python/pyro-ppl-1.8[${PYTHON_USEDEP}] )
	test? ( dev-python/pytest[${PYTHON_USEDEP}] )
	dev-python/scikit-learn[${PYTHON_USEDEP}]
	>=dev-python/scipy-1.6.0[${PYTHON_USEDEP}]
	examples? ( dev-python/scipy[${PYTHON_USEDEP}] )
	dev? ( dev-python/setuptools-scm[${PYTHON_USEDEP}] )
	docs? ( <=dev-python/setuptools-scm-7.1.0[${PYTHON_USEDEP}] )
	docs? ( <=dev-python/sphinx-6.2.1[${PYTHON_USEDEP}] )
	docs? ( <=dev-python/sphinx-autodoc-typehints-1.23.0[${PYTHON_USEDEP}] )
	docs? ( <dev-python/sphinx-rtd-theme-0.5[${PYTHON_USEDEP}] )
	examples? ( dev-python/torchvision[${PYTHON_USEDEP}] )
	examples? ( dev-python/tqdm[${PYTHON_USEDEP}] )
	dev? ( dev-python/twine[${PYTHON_USEDEP}] )
	dev? ( dev-python/ufmt[${PYTHON_USEDEP}] )
	docs? ( <=dev-python/uncompyle6-3.9.0[${PYTHON_USEDEP}] )
	dev? ( dev-vcs/pre-commit[${PYTHON_USEDEP}] )
"
RDEPEND="${GENERATED_DEPEND}"

distutils_enable_tests pytest