# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
PYPI_NO_NORMALIZE=1
GENERATED_IUSE="all deeplearning docs full plotting sarimax test"
IUSE="${GENERATED_IUSE}"

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/skforecast/"

LICENSE=""
SLOT="0"
KEYWORDS="amd64 arm64"

GENERATED_DEPEND="
	docs? ( ~dev-python/black-24.10.0[${PYTHON_USEDEP}] )
	>=dev-python/joblib-1.1[${PYTHON_USEDEP}]
	docs? ( ~dev-python/jupyter-contrib-nbextensions-0.7.0[${PYTHON_USEDEP}] )
	all? ( <dev-python/keras-4.0[${PYTHON_USEDEP}] )
	deeplearning? ( <dev-python/keras-4.0[${PYTHON_USEDEP}] )
	full? ( <dev-python/keras-4.0[${PYTHON_USEDEP}] )
	test? ( <dev-python/lightgbm-4.6[${PYTHON_USEDEP}] )
	all? ( <dev-python/matplotlib-3.10[${PYTHON_USEDEP}] )
	deeplearning? ( <dev-python/matplotlib-3.10[${PYTHON_USEDEP}] )
	full? ( <dev-python/matplotlib-3.10[${PYTHON_USEDEP}] )
	plotting? ( <dev-python/matplotlib-3.10[${PYTHON_USEDEP}] )
	docs? ( ~dev-python/mike-2.1.3[${PYTHON_USEDEP}] )
	docs? ( ~dev-python/mkdocs-1.6.1[${PYTHON_USEDEP}] )
	docs? ( ~dev-python/mkdocs-jupyter-0.25.0[${PYTHON_USEDEP}] )
	docs? ( ~dev-python/mkdocs-material-9.5.39[${PYTHON_USEDEP}] )
	docs? ( ~dev-python/mkdocstrings-0.26.1[${PYTHON_USEDEP}] )
	docs? ( ~dev-python/mkdocstrings-python-1.11.1[${PYTHON_USEDEP}] )
	docs? ( ~dev-python/notebook-6.4.12[${PYTHON_USEDEP}] )
	>=dev-python/numba-0.59[${PYTHON_USEDEP}]
	>=dev-python/numpy-1.22[${PYTHON_USEDEP}]
	>=dev-python/optuna-2.10[${PYTHON_USEDEP}]
	>=dev-python/pandas-1.5[${PYTHON_USEDEP}]
	test? ( >=dev-python/pandas-1.5[parquet,${PYTHON_USEDEP}] )
	test? ( >=dev-python/pytest-7.3[${PYTHON_USEDEP}] )
	test? ( >=dev-python/pytest-cov-4.1[${PYTHON_USEDEP}] )
	test? ( >=dev-python/pytest-xdist-3.3[${PYTHON_USEDEP}] )
	>=dev-python/scikit-learn-1.2[${PYTHON_USEDEP}]
	all? ( <dev-python/seaborn-0.14[${PYTHON_USEDEP}] )
	full? ( <dev-python/seaborn-0.14[${PYTHON_USEDEP}] )
	plotting? ( <dev-python/seaborn-0.14[${PYTHON_USEDEP}] )
	all? ( <dev-python/statsmodels-0.15[${PYTHON_USEDEP}] )
	full? ( <dev-python/statsmodels-0.15[${PYTHON_USEDEP}] )
	plotting? ( <dev-python/statsmodels-0.15[${PYTHON_USEDEP}] )
	sarimax? ( <dev-python/statsmodels-0.15[${PYTHON_USEDEP}] )
	test? ( <dev-python/tensorflow-2.19[${PYTHON_USEDEP}] )
	test? ( >=dev-python/tomli-2.0[${PYTHON_USEDEP}] )
	test? ( <dev-python/torch-2.6[${PYTHON_USEDEP}] )
	>=dev-python/tqdm-4.57[${PYTHON_USEDEP}]
"
RDEPEND="${GENERATED_DEPEND}"

distutils_enable_tests pytest