# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
GENERATED_IUSE="aiobotocore apache-hive cncf-kubernetes exasol ftp google imap microsoft-azure mongo openlineage pandas python3-saml s3fs salesforce ssh"
IUSE="${GENERATED_IUSE}"

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/apache-airflow-providers-amazon/"

LICENSE=""
SLOT="0"
KEYWORDS="amd64 arm64"

GENERATED_DEPEND="
	aiobotocore? ( >=dev-python/aiobotocore-2.13.0[boto3,${PYTHON_USEDEP}] )
	>=dev-python/apache-airflow-2.9.0[${PYTHON_USEDEP}]
	apache-hive? ( dev-python/apache-airflow-providers-apache-hive[${PYTHON_USEDEP}] )
	cncf-kubernetes? ( >=dev-python/apache-airflow-providers-cncf-kubernetes-7.2.0[${PYTHON_USEDEP}] )
	>=dev-python/apache-airflow-providers-common-compat-1.3.0[${PYTHON_USEDEP}]
	>=dev-python/apache-airflow-providers-common-sql-1.20.0[${PYTHON_USEDEP}]
	exasol? ( dev-python/apache-airflow-providers-exasol[${PYTHON_USEDEP}] )
	ftp? ( dev-python/apache-airflow-providers-ftp[${PYTHON_USEDEP}] )
	google? ( dev-python/apache-airflow-providers-google[${PYTHON_USEDEP}] )
	dev-python/apache-airflow-providers-http[${PYTHON_USEDEP}]
	imap? ( dev-python/apache-airflow-providers-imap[${PYTHON_USEDEP}] )
	microsoft-azure? ( dev-python/apache-airflow-providers-microsoft-azure[${PYTHON_USEDEP}] )
	mongo? ( dev-python/apache-airflow-providers-mongo[${PYTHON_USEDEP}] )
	openlineage? ( dev-python/apache-airflow-providers-openlineage[${PYTHON_USEDEP}] )
	salesforce? ( dev-python/apache-airflow-providers-salesforce[${PYTHON_USEDEP}] )
	ssh? ( dev-python/apache-airflow-providers-ssh[${PYTHON_USEDEP}] )
	>=dev-python/asgiref-2.3.0[${PYTHON_USEDEP}]
	>=dev-python/boto3-1.34.90[${PYTHON_USEDEP}]
	>=dev-python/botocore-1.34.90[${PYTHON_USEDEP}]
	>=dev-python/inflection-0.5.1[${PYTHON_USEDEP}]
	>=dev-python/jmespath-0.7.0[${PYTHON_USEDEP}]
	>=dev-python/jsonpath-ng-1.5.3[${PYTHON_USEDEP}]
	pandas? ( <dev-python/pandas-2.2[${PYTHON_USEDEP}] )
	pandas? ( <dev-python/pandas-2.2[${PYTHON_USEDEP}] )
	>=dev-python/pyathena-3.0.10[${PYTHON_USEDEP}]
	>=dev-python/python3-saml-1.16.0[${PYTHON_USEDEP}]
	python3-saml? ( >=dev-python/python3-saml-1.16.0[${PYTHON_USEDEP}] )
	>=dev-python/redshift-connector-2.0.918[${PYTHON_USEDEP}]
	s3fs? ( >=dev-python/s3fs-2023.10.0[${PYTHON_USEDEP}] )
	!=dev-python/watchtower-3.3.0[${PYTHON_USEDEP}]
"
RDEPEND="${GENERATED_DEPEND}"

distutils_enable_tests pytest
