# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
PYPI_NO_NORMALIZE=1
GENERATED_IUSE="test"
IUSE="${GENERATED_IUSE}"

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/sphinx-autobuild/"

LICENSE=""
SLOT="0"
KEYWORDS="amd64 arm64"

GENERATED_DEPEND="
	>=dev-python/colorama-0.4.6[${PYTHON_USEDEP}]
	test? ( dev-python/httpx[${PYTHON_USEDEP}] )
	test? ( >=dev-python/pytest-6[${PYTHON_USEDEP}] )
	dev-python/sphinx[${PYTHON_USEDEP}]
	>=dev-python/starlette-0.35[${PYTHON_USEDEP}]
	>=dev-python/uvicorn-0.25[${PYTHON_USEDEP}]
	>=dev-python/watchfiles-0.20[${PYTHON_USEDEP}]
	>=dev-python/websockets-11[${PYTHON_USEDEP}]
"
RDEPEND="${GENERATED_DEPEND}"

distutils_enable_tests pytest