# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
PYPI_NO_NORMALIZE=1
GENERATED_IUSE="adlfs daft duckdb gcsfs glue hive pandas pyarrow s3fs snappy sql-postgres zstandard"
IUSE="${GENERATED_IUSE}"

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/pyiceberg/"

LICENSE="Apache-2.0"
SLOT="0"
KEYWORDS="amd64 arm64"

GENERATED_DEPEND="${PYTHON_DEPS}
	adlfs? ( >=dev-python/adlfs-2023.1.0[${PYTHON_USEDEP}] )
	glue? ( >=dev-python/boto3-1.24.59[${PYTHON_USEDEP}] )
	<dev-python/cachetools-6.0.0[${PYTHON_USEDEP}]
	<dev-python/click-9.0.0[${PYTHON_USEDEP}]
	duckdb? ( <dev-python/duckdb-2.0.0[${PYTHON_USEDEP}] )
	>=dev-python/fsspec-2023.1.0[${PYTHON_USEDEP}]
	gcsfs? ( >=dev-python/gcsfs-2023.1.0[${PYTHON_USEDEP}] )
	daft? ( >=dev-python/getdaft-0.2.12[${PYTHON_USEDEP}] )
	<dev-python/mmh3-6.0.0[${PYTHON_USEDEP}]
	glue? ( >=dev-python/mypy-boto3-glue-1.28.18[${PYTHON_USEDEP}] )
	pandas? ( <dev-python/pandas-3.0.0[${PYTHON_USEDEP}] )
	sql-postgres? ( >=dev-python/psycopg2-binary-2.9.6[${PYTHON_USEDEP}] )
	pyarrow? ( <dev-python/pyarrow-19.0.0[${PYTHON_USEDEP}] )
	!=dev-python/pydantic-2.4.0[${PYTHON_USEDEP}]
	<dev-python/pyparsing-4.0.0[${PYTHON_USEDEP}]
	snappy? ( <dev-python/python-snappy-1.0.0[${PYTHON_USEDEP}] )
	~dev-python/ray-2.10.0[${PYTHON_USEDEP}]
	<dev-python/requests-3.0.0[${PYTHON_USEDEP}]
	<dev-python/rich-14.0.0[${PYTHON_USEDEP}]
	s3fs? ( >=dev-python/s3fs-2023.1.0[${PYTHON_USEDEP}] )
	~dev-python/sortedcontainers-2.4.0[${PYTHON_USEDEP}]
	sql-postgres? ( <dev-python/sqlalchemy-3.0.0[${PYTHON_USEDEP}] )
	<dev-python/strictyaml-2.0.0[${PYTHON_USEDEP}]
	<dev-python/tenacity-10.0.0[${PYTHON_USEDEP}]
	hive? ( <dev-python/thrift-1.0.0[${PYTHON_USEDEP}] )
	zstandard? ( <dev-python/zstandard-1.0.0[${PYTHON_USEDEP}] )
"
RDEPEND="${GENERATED_DEPEND}"

distutils_enable_tests pytest
