# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
PYPI_NO_NORMALIZE=1
GENERATED_IUSE="cli device full litmus quantizer server serving test tool"
IUSE="${GENERATED_IUSE}"

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/furiosa-sdk/"

LICENSE=""
SLOT="0"
KEYWORDS="amd64 arm64"

REQUIRES_DIST="
	furiosa-cli==0.10.*
	furiosa-cli==0.10.*; extra == 'cli'
	furiosa-cli==0.10.*; extra == 'full'
	furiosa-device==0.10.*; extra == 'device'
	furiosa-device==0.10.*; extra == 'full'
	furiosa-litmus==0.10.*; extra == 'full'
	furiosa-litmus==0.10.*; extra == 'litmus'
	furiosa-optimizer==0.10.*; extra == 'full'
	furiosa-optimizer==0.10.*; extra == 'quantizer'
	furiosa-quantizer==0.10.*; extra == 'full'
	furiosa-quantizer==0.10.*; extra == 'quantizer'
	furiosa-runtime==0.10.*
	furiosa-server==0.10.*; extra == 'full'
	furiosa-server==0.10.*; extra == 'server'
	furiosa-serving==0.10.*; extra == 'full'
	furiosa-serving==0.10.*; extra == 'serving'
	furiosa-tools==0.10.*
	furiosa-tools==0.10.*; extra == 'full'
	furiosa-tools==0.10.*; extra == 'tool'
	mypy; extra == 'test'
	pytest; extra == 'test'
	ruff; extra == 'test'
"
GENERATED_RDEPEND="${RDEPEND}
	=dev-python/furiosa-cli-0.10*[${PYTHON_USEDEP}]
	cli? ( =dev-python/furiosa-cli-0.10*[${PYTHON_USEDEP}] )
	full? ( =dev-python/furiosa-cli-0.10*[${PYTHON_USEDEP}] )
	device? ( =dev-python/furiosa-device-0.10*[${PYTHON_USEDEP}] )
	full? ( =dev-python/furiosa-device-0.10*[${PYTHON_USEDEP}] )
	full? ( =dev-python/furiosa-litmus-0.10*[${PYTHON_USEDEP}] )
	litmus? ( =dev-python/furiosa-litmus-0.10*[${PYTHON_USEDEP}] )
	full? ( =dev-python/furiosa-optimizer-0.10*[${PYTHON_USEDEP}] )
	quantizer? ( =dev-python/furiosa-optimizer-0.10*[${PYTHON_USEDEP}] )
	full? ( =dev-python/furiosa-quantizer-0.10*[${PYTHON_USEDEP}] )
	quantizer? ( =dev-python/furiosa-quantizer-0.10*[${PYTHON_USEDEP}] )
	=dev-python/furiosa-runtime-0.10*[${PYTHON_USEDEP}]
	full? ( =dev-python/furiosa-server-0.10*[${PYTHON_USEDEP}] )
	server? ( =dev-python/furiosa-server-0.10*[${PYTHON_USEDEP}] )
	full? ( =dev-python/furiosa-serving-0.10*[${PYTHON_USEDEP}] )
	serving? ( =dev-python/furiosa-serving-0.10*[${PYTHON_USEDEP}] )
	=dev-python/furiosa-tools-0.10*[${PYTHON_USEDEP}]
	full? ( =dev-python/furiosa-tools-0.10*[${PYTHON_USEDEP}] )
	tool? ( =dev-python/furiosa-tools-0.10*[${PYTHON_USEDEP}] )
"
RDEPEND="${GENERATED_RDEPEND}"

distutils_enable_tests pytest
GENERATED_BDEPEND="${BDEPEND}
	test? (
		dev-python/mypy[${PYTHON_USEDEP}]
		dev-python/pytest[${PYTHON_USEDEP}]
		dev-python/ruff[${PYTHON_USEDEP}]
	)
"
BDEPEND="${GENERATED_BDEPEND}"
