# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
GENERATED_IUSE="all docs"
IUSE="${GENERATED_IUSE}"

PYPI_NO_NORMALIZE=1
inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/nc-time-axis/"

LICENSE=""
SLOT="0"
KEYWORDS="amd64 arm64"

REQUIRES_DIST="
	cftime (>=1.5)
	codecov ; extra == 'all'
	codecov ; extra == 'test'
	ipython ; extra == 'all'
	ipython ; extra == 'docs'
	matplotlib
	numpy
	numpydoc ; extra == 'all'
	numpydoc ; extra == 'docs'
	pre-commit ; extra == 'all'
	pytest (>=6.0) ; extra == 'all'
	pytest (>=6.0) ; extra == 'test'
	pytest-cov ; extra == 'all'
	pytest-cov ; extra == 'test'
	sphinx ; extra == 'all'
	sphinx ; extra == 'docs'
	sphinx-rtd-theme ; extra == 'all'
	sphinx-rtd-theme ; extra == 'docs'
"
GENERATED_RDEPEND="${RDEPEND}
	>=dev-python/cftime-1.5[${PYTHON_USEDEP}]
	all? ( dev-python/codecov[${PYTHON_USEDEP}] )
	all? ( dev-python/ipython[${PYTHON_USEDEP}] )
	docs? ( dev-python/ipython[${PYTHON_USEDEP}] )
	dev-python/matplotlib[${PYTHON_USEDEP}]
	dev-python/numpy[${PYTHON_USEDEP}]
	all? ( dev-python/numpydoc[${PYTHON_USEDEP}] )
	docs? ( dev-python/numpydoc[${PYTHON_USEDEP}] )
	all? ( >=dev-python/pytest-6.0[${PYTHON_USEDEP}] )
	all? ( dev-python/pytest-cov[${PYTHON_USEDEP}] )
	all? ( dev-python/sphinx[${PYTHON_USEDEP}] )
	docs? ( dev-python/sphinx[${PYTHON_USEDEP}] )
	all? ( dev-python/sphinx-rtd-theme[${PYTHON_USEDEP}] )
	docs? ( dev-python/sphinx-rtd-theme[${PYTHON_USEDEP}] )
	all? ( dev-vcs/pre-commit[${PYTHON_USEDEP}] )
"
RDEPEND="${GENERATED_RDEPEND}"

distutils_enable_tests pytest
GENERATED_BDEPEND="${BDEPEND}
	test? (
		dev-python/codecov[${PYTHON_USEDEP}]
		>=dev-python/pytest-6.0[${PYTHON_USEDEP}]
		dev-python/pytest-cov[${PYTHON_USEDEP}]
	)
"
BDEPEND="${GENERATED_BDEPEND}"
