# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
PYPI_NO_NORMALIZE=1
GENERATED_IUSE="testing"
IUSE="${GENERATED_IUSE}"

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/orbax-checkpoint/"

LICENSE=""
SLOT="0"
KEYWORDS="amd64 arm64"

GENERATED_DEPEND="
	dev-python/absl-py[${PYTHON_USEDEP}]
	testing? ( dev-python/chex[${PYTHON_USEDEP}] )
	dev-python/etils[epath,epy,${PYTHON_USEDEP}]
	testing? ( dev-python/flax[${PYTHON_USEDEP}] )
	testing? ( dev-python/google-cloud-logging[${PYTHON_USEDEP}] )
	dev-python/humanize[${PYTHON_USEDEP}]
	>=dev-python/jax-0.4.34[${PYTHON_USEDEP}]
	testing? ( dev-python/mock[${PYTHON_USEDEP}] )
	dev-python/msgpack[${PYTHON_USEDEP}]
	dev-python/nest-asyncio[${PYTHON_USEDEP}]
	dev-python/numpy[${PYTHON_USEDEP}]
	dev-python/protobuf[${PYTHON_USEDEP}]
	testing? ( dev-python/pytest[${PYTHON_USEDEP}] )
	testing? ( dev-python/pytest-xdist[${PYTHON_USEDEP}] )
	dev-python/pyyaml[${PYTHON_USEDEP}]
	>=dev-python/simplejson-3.16.0[${PYTHON_USEDEP}]
	>=dev-python/tensorstore-0.1.68[${PYTHON_USEDEP}]
	dev-python/typing-extensions[${PYTHON_USEDEP}]
"
RDEPEND="${GENERATED_DEPEND}"

distutils_enable_tests pytest