# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
GENERATED_IUSE="cli"
IUSE="${GENERATED_IUSE}"

inherit distutils-r1 pypi
SRC_URI="$(pypi_sdist_url --no-normalize ${PN} 0.2.0b2)"
S="${WORKDIR}/${PN}-0.2.0b2"

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/sphinx-theme-builder/"

LICENSE=""
SLOT="0"
KEYWORDS="amd64 arm64"

REQUIRES_DIST="
	build ; extra == 'cli'
	click ; extra == 'cli'
	nodeenv
	packaging
	pyproject-metadata
	rich
	setuptools
	sphinx-autobuild ; extra == 'cli'
	tomli ; python_version < '3.11'
	typing_extensions ; python_version <= '3.7'
"
GENERATED_RDEPEND="${RDEPEND}
	cli? ( dev-python/build[${PYTHON_USEDEP}] )
	cli? ( dev-python/click[${PYTHON_USEDEP}] )
	dev-python/nodeenv[${PYTHON_USEDEP}]
	dev-python/packaging[${PYTHON_USEDEP}]
	dev-python/pyproject-metadata[${PYTHON_USEDEP}]
	dev-python/rich[${PYTHON_USEDEP}]
	dev-python/setuptools[${PYTHON_USEDEP}]
	cli? ( dev-python/sphinx-autobuild[${PYTHON_USEDEP}] )
"
RDEPEND="${GENERATED_RDEPEND}"

distutils_enable_tests pytest
