# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
GENERATED_IUSE="gssapi"
IUSE="${GENERATED_IUSE}"

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/dvc-ssh/"

LICENSE=""
SLOT="0"
KEYWORDS="amd64 arm64"

REQUIRES_DIST="
	dvc
	dvc-ssh[tests]; extra == "dev"
	dvc[testing]; extra == "tests"
	mypy==1.14.1; extra == "dev"
	pytest-cov>=4.1.0; extra == "tests"
	pytest-docker<4,>=1; extra == "tests"
	pytest-mock; extra == "tests"
	pytest-xdist>=3.2; extra == "tests"
	pytest<9,>=7; extra == "tests"
	sshfs[bcrypt]>=2023.4.1
	sshfs[gssapi]>=2021.11.2; extra == "gssapi"
"
GENERATED_RDEPEND="${RDEPEND}
	dev-python/dvc[${PYTHON_USEDEP}]
	>=dev-python/sshfs-2023.4.1[bcrypt,${PYTHON_USEDEP}]
	gssapi? ( >=dev-python/sshfs-2021.11.2[gssapi,${PYTHON_USEDEP}] )
"
RDEPEND="${GENERATED_RDEPEND}"

distutils_enable_tests pytest
GENERATED_BDEPEND="${BDEPEND}
	test? (
		dev-python/dvc[testing,${PYTHON_USEDEP}]
		dev-python/dvc-ssh[tests,${PYTHON_USEDEP}]
		~dev-python/mypy-1.14.1[${PYTHON_USEDEP}]
		>=dev-python/pytest-7[${PYTHON_USEDEP}] <dev-python/pytest-9[${PYTHON_USEDEP}]
		>=dev-python/pytest-cov-4.1.0[${PYTHON_USEDEP}]
		>=dev-python/pytest-docker-1[${PYTHON_USEDEP}] <dev-python/pytest-docker-4[${PYTHON_USEDEP}]
		dev-python/pytest-mock[${PYTHON_USEDEP}]
		>=dev-python/pytest-xdist-3.2[${PYTHON_USEDEP}]
	)
"
BDEPEND="${GENERATED_BDEPEND}"
