# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/langchain-groq/"

LICENSE="MIT"
SLOT="0"
KEYWORDS="amd64 arm64"

REQUIRES_DIST="
	groq<1,>=0.4.1
	langchain-core<0.4.0,>=0.3.33
"
GENERATED_RDEPEND="${RDEPEND}
	>=dev-python/groq-0.4.1[${PYTHON_USEDEP}] <dev-python/groq-1[${PYTHON_USEDEP}]
	>=dev-python/langchain-core-0.3.33[${PYTHON_USEDEP}] <dev-python/langchain-core-0.4.0[${PYTHON_USEDEP}]
"
RDEPEND="${GENERATED_RDEPEND}"

distutils_enable_tests pytest

