# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
IUSE=""

inherit distutils-r1 pypi
SRC_URI="$(pypi_sdist_url ${PN} 0.3.0.post1)"
S="${WORKDIR}/${PN}-0.3.0.post1"

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/dict2css/"

LICENSE="MIT"
SLOT="0"
KEYWORDS="amd64 arm64"

GENERATED_DEPEND="${RDEPEND}
	>=dev-python/cssutils-2.2.0[${PYTHON_USEDEP}]
	>=dev-python/domdf-python-tools-2.2.0[${PYTHON_USEDEP}]
"
RDEPEND="${GENERATED_DEPEND}"

distutils_enable_tests pytest
