# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
PYPI_NO_NORMALIZE=1
GENERATED_IUSE="dev doc plotly plotting style test"
IUSE="${GENERATED_IUSE}"

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/nilearn/"

LICENSE=""
SLOT="0"
KEYWORDS="amd64 arm64"

GENERATED_DEPEND="
	dev? ( dev-python/coverage[${PYTHON_USEDEP}] )
	test? ( dev-python/coverage[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/furo-2024.8.6[${PYTHON_USEDEP}] )
	doc? ( >=dev-python/furo-2024.8.6[${PYTHON_USEDEP}] )
	>=dev-python/joblib-1.2.0[${PYTHON_USEDEP}]
	dev-python/kaleido[${PYTHON_USEDEP}]
	dev-python/kaleido[${PYTHON_USEDEP}]
	dev-python/kaleido[${PYTHON_USEDEP}]
	dev-python/kaleido[${PYTHON_USEDEP}]
	~dev-python/kaleido-0.1.0_p1[${PYTHON_USEDEP}]
	~dev-python/kaleido-0.1.0_p1[${PYTHON_USEDEP}]
	~dev-python/kaleido-0.1.0_p1[${PYTHON_USEDEP}]
	~dev-python/kaleido-0.1.0_p1[${PYTHON_USEDEP}]
	dev-python/lxml[${PYTHON_USEDEP}]
	dev? ( >=dev-python/matplotlib-3.3.0[${PYTHON_USEDEP}] )
	doc? ( >=dev-python/matplotlib-3.3.0[${PYTHON_USEDEP}] )
	plotly? ( >=dev-python/matplotlib-3.3.0[${PYTHON_USEDEP}] )
	plotting? ( >=dev-python/matplotlib-3.3.0[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/memory-profiler-0.61.0[${PYTHON_USEDEP}] )
	doc? ( >=dev-python/memory-profiler-0.61.0[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/myst-parser-3.0.1[${PYTHON_USEDEP}] )
	doc? ( >=dev-python/myst-parser-3.0.1[${PYTHON_USEDEP}] )
	>=dev-python/nibabel-5.2.0[${PYTHON_USEDEP}]
	>=dev-python/numpy-1.22.4[${PYTHON_USEDEP}]
	dev? ( >=dev-python/numpydoc-1.8.0[${PYTHON_USEDEP}] )
	doc? ( >=dev-python/numpydoc-1.8.0[${PYTHON_USEDEP}] )
	dev-python/packaging[${PYTHON_USEDEP}]
	>=dev-python/pandas-2.2.0[${PYTHON_USEDEP}]
	dev? ( dev-python/plotly[${PYTHON_USEDEP}] )
	doc? ( dev-python/plotly[${PYTHON_USEDEP}] )
	plotly? ( dev-python/plotly[${PYTHON_USEDEP}] )
	plotting? ( dev-python/plotly[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/pytest-6.0.0[${PYTHON_USEDEP}] )
	test? ( >=dev-python/pytest-6.0.0[${PYTHON_USEDEP}] )
	dev? ( dev-python/pytest-cov[${PYTHON_USEDEP}] )
	test? ( dev-python/pytest-cov[${PYTHON_USEDEP}] )
	dev? ( dev-python/pytest-randomly[${PYTHON_USEDEP}] )
	test? ( dev-python/pytest-randomly[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/pytest-reporter-html1-0.9.2[${PYTHON_USEDEP}] )
	test? ( >=dev-python/pytest-reporter-html1-0.9.2[${PYTHON_USEDEP}] )
	dev? ( dev-python/pytest-xdist[psutil,${PYTHON_USEDEP}] )
	test? ( dev-python/pytest-xdist[psutil,${PYTHON_USEDEP}] )
	>=dev-python/requests-2.25.0[${PYTHON_USEDEP}]
	dev? ( >=dev-python/ruamel-yaml-0.18.6[${PYTHON_USEDEP}] )
	doc? ( >=dev-python/ruamel-yaml-0.18.6[${PYTHON_USEDEP}] )
	>=dev-python/scikit-learn-1.4.0[${PYTHON_USEDEP}]
	>=dev-python/scipy-1.8.0[${PYTHON_USEDEP}]
	dev? ( >=dev-python/sphinx-7.4.7[${PYTHON_USEDEP}] )
	doc? ( >=dev-python/sphinx-7.4.7[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/sphinx-copybutton-0.5.2[${PYTHON_USEDEP}] )
	doc? ( >=dev-python/sphinx-copybutton-0.5.2[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/sphinx-design-0.6.1[${PYTHON_USEDEP}] )
	doc? ( >=dev-python/sphinx-design-0.6.1[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/sphinx-gallery-0.18.0[${PYTHON_USEDEP}] )
	doc? ( >=dev-python/sphinx-gallery-0.18.0[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/sphinxcontrib-bibtex-2.6.3[${PYTHON_USEDEP}] )
	doc? ( >=dev-python/sphinxcontrib-bibtex-2.6.3[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/sphinxext-opengraph-0.9.1[${PYTHON_USEDEP}] )
	doc? ( >=dev-python/sphinxext-opengraph-0.9.1[${PYTHON_USEDEP}] )
	dev? ( dev-python/tox[${PYTHON_USEDEP}] )
	style? ( dev-python/tox[${PYTHON_USEDEP}] )
	test? ( dev-python/tox[${PYTHON_USEDEP}] )
"
RDEPEND="${GENERATED_DEPEND}"

distutils_enable_tests pytest