# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
IUSE=""

PYPI_NO_NORMALIZE=1
inherit distutils-r1 pypi
SRC_URI="$(pypi_sdist_url --no-normalize ${PN} 21.9.2)"
S="${WORKDIR}/${PN}-21.9.2"

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/catalyst-codestyle/"

LICENSE=""
SLOT="0"
KEYWORDS="amd64 arm64"

GENERATED_DEPEND="${RDEPEND}
	>=dev-python/black-19_beta0[${PYTHON_USEDEP}]
	<dev-python/darglint-2.0[${PYTHON_USEDEP}]
	<dev-python/flake8-4.0[${PYTHON_USEDEP}]
	<dev-python/flake8-blind-except-0.2[${PYTHON_USEDEP}]
	<dev-python/flake8-broken-line-0.4[${PYTHON_USEDEP}]
	<dev-python/flake8-bugbear-22.0[${PYTHON_USEDEP}]
	<dev-python/flake8-comprehensions-4.0[${PYTHON_USEDEP}]
	<dev-python/flake8-debugger-5.0[${PYTHON_USEDEP}]
	<dev-python/flake8-docstrings-2.0[${PYTHON_USEDEP}]
	<dev-python/flake8-quotes-4.0[${PYTHON_USEDEP}]
	<dev-python/flake8-rst-docstrings-0.3.0[${PYTHON_USEDEP}]
	<dev-python/flake8-string-format-0.4[${PYTHON_USEDEP}]
	<dev-python/isort-6.0[${PYTHON_USEDEP}]
	<dev-python/nitpick-0.28[${PYTHON_USEDEP}]
	<dev-python/pep8-naming-0.13[${PYTHON_USEDEP}]
"
RDEPEND="${GENERATED_DEPEND}"

distutils_enable_tests pytest
