# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
IUSE=""

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/watchtower/"

LICENSE=""
SLOT="0"
KEYWORDS="amd64 arm64"

GENERATED_DEPEND="${RDEPEND}
	<dev-python/boto3-2[${PYTHON_USEDEP}]
"
RDEPEND="${GENERATED_DEPEND}"

distutils_enable_tests pytest
BDEPEND+=" test? (
	dev-python/build[${PYTHON_USEDEP}]
	dev-python/coverage[${PYTHON_USEDEP}]
	<dev-python/flake8-5[${PYTHON_USEDEP}]
	dev-python/mypy[${PYTHON_USEDEP}]
	<dev-python/pyyaml-6[${PYTHON_USEDEP}]
	dev-python/wheel[${PYTHON_USEDEP}]
)"
