# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
PYPI_NO_NORMALIZE=1
GENERATED_IUSE=""
IUSE="${GENERATED_IUSE}"

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/submitit/"

LICENSE=""
SLOT="0"
KEYWORDS="amd64 arm64"

GENERATED_DEPEND="${PYTHON_DEPS}
	>=dev-python/cloudpickle-1.2.1[${PYTHON_USEDEP}]
	>=dev-python/typing-extensions-3.7.4.2[${PYTHON_USEDEP}]
"
RDEPEND="${GENERATED_DEPEND}"

distutils_enable_tests pytest
BDEPEND+=" test? (
	~dev-python/black-23.3.0[${PYTHON_USEDEP}]
	>=dev-python/coverage-5.1[toml,${PYTHON_USEDEP}]
	>=dev-python/flit-3.5.1[${PYTHON_USEDEP}]
	~dev-python/isort-5.11.5[${PYTHON_USEDEP}]
	>=dev-python/mypy-1.4.1[${PYTHON_USEDEP}]
	>=dev-python/pylint-3.0.0[${PYTHON_USEDEP}]
	>=dev-python/pytest-7.4.2[${PYTHON_USEDEP}]
	>=dev-python/pytest-asyncio-0.15.0[${PYTHON_USEDEP}]
	>=dev-python/pytest-cov-4.1.0[${PYTHON_USEDEP}]
	>=dev-vcs/pre-commit-1.15.2[${PYTHON_USEDEP}]
)"
