# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
PYPI_NO_NORMALIZE=1
GENERATED_IUSE="db"
IUSE="${GENERATED_IUSE}"

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/oci-cli/"

LICENSE=""
SLOT="0"
KEYWORDS="amd64 arm64"

GENERATED_DEPEND="
	>=dev-python/arrow-1.0.0[${PYTHON_USEDEP}]
	dev-python/certifi[${PYTHON_USEDEP}]
	~dev-python/click-8.0.4[${PYTHON_USEDEP}]
	<dev-python/cryptography-46.0.0[${PYTHON_USEDEP}]
	db? ( ~dev-python/cx-oracle-8.3[${PYTHON_USEDEP}] )
	~dev-python/jmespath-0.10.0[${PYTHON_USEDEP}]
	~dev-python/oci-2.143.0[${PYTHON_USEDEP}]
	<dev-python/pyopenssl-25.0.0[${PYTHON_USEDEP}]
	<dev-python/python-dateutil-3.0.0[${PYTHON_USEDEP}]
	>=dev-python/pytz-2016.10[${PYTHON_USEDEP}]
	<=dev-python/pyyaml-6.0.1[${PYTHON_USEDEP}]
	$(python_gen_cond_dep '>dev-python/setuptools-70.0.0[${PYTHON_USEDEP}]' python3_12)
	>=dev-python/six-1.15.0[${PYTHON_USEDEP}]
	~dev-python/terminaltables-3.1.10[${PYTHON_USEDEP}]
"
RDEPEND="${GENERATED_DEPEND}"

distutils_enable_tests pytest