# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
PYPI_NO_NORMALIZE=1
GENERATED_IUSE="all dask dev plotly polars spark"
IUSE="${GENERATED_IUSE}"

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/statsforecast/"

LICENSE=""
SLOT="0"
KEYWORDS="amd64 arm64"

GENERATED_DEPEND="
	all? ( dev-python/black[${PYTHON_USEDEP}] )
	dev? ( dev-python/black[${PYTHON_USEDEP}] )
	dev-python/cloudpickle[${PYTHON_USEDEP}]
	>=dev-python/coreforecast-0.0.12[${PYTHON_USEDEP}]
	all? ( dev-python/datasetsforecast[${PYTHON_USEDEP}] )
	dev? ( dev-python/datasetsforecast[${PYTHON_USEDEP}] )
	all? ( dev-python/fire[${PYTHON_USEDEP}] )
	dev? ( dev-python/fire[${PYTHON_USEDEP}] )
	$(python_gen_cond_dep '>=dev-python/fugue-0.8.1[ray,${PYTHON_USEDEP}]' python3_12)
	$(python_gen_cond_dep '>=dev-python/fugue-0.8.1[ray,${PYTHON_USEDEP}]' python3_12)
	>=dev-python/fugue-0.8.1[${PYTHON_USEDEP}]
	all? ( >=dev-python/fugue-0.8.1[dask,${PYTHON_USEDEP}] )
	all? ( >=dev-python/fugue-0.8.1[spark,${PYTHON_USEDEP}] )
	dask? ( >=dev-python/fugue-0.8.1[dask,${PYTHON_USEDEP}] )
	spark? ( >=dev-python/fugue-0.8.1[spark,${PYTHON_USEDEP}] )
	all? ( ~dev-python/nbdev-2.3.25[${PYTHON_USEDEP}] )
	dev? ( ~dev-python/nbdev-2.3.25[${PYTHON_USEDEP}] )
	all? ( dev-python/nbdev-plotly[${PYTHON_USEDEP}] )
	dev? ( dev-python/nbdev-plotly[${PYTHON_USEDEP}] )
	all? ( dev-python/nbformat[${PYTHON_USEDEP}] )
	dev? ( dev-python/nbformat[${PYTHON_USEDEP}] )
	>=dev-python/numba-0.55.0[${PYTHON_USEDEP}]
	$(python_gen_cond_dep '<dev-python/numpy-2[${PYTHON_USEDEP}]' python3_12)
	$(python_gen_cond_dep '<dev-python/numpy-2[${PYTHON_USEDEP}]' python3_12)
	>=dev-python/numpy-1.21.6[${PYTHON_USEDEP}]
	$(python_gen_cond_dep '<dev-python/pandas-2.2[${PYTHON_USEDEP}]' python3_12)
	$(python_gen_cond_dep '<dev-python/pandas-2.2[${PYTHON_USEDEP}]' python3_12)
	>=dev-python/pandas-1.3.5[${PYTHON_USEDEP}]
	all? ( dev-python/pandas[plot,${PYTHON_USEDEP}] )
	dev? ( dev-python/pandas[plot,${PYTHON_USEDEP}] )
	all? ( dev-python/plotly[${PYTHON_USEDEP}] )
	plotly? ( dev-python/plotly[${PYTHON_USEDEP}] )
	all? ( dev-python/plotly-resampler[${PYTHON_USEDEP}] )
	plotly? ( dev-python/plotly-resampler[${PYTHON_USEDEP}] )
	all? ( dev-python/pmdarima[${PYTHON_USEDEP}] )
	dev? ( dev-python/pmdarima[${PYTHON_USEDEP}] )
	all? ( dev-python/polars[numpy,${PYTHON_USEDEP}] )
	dev? ( dev-python/polars[numpy,${PYTHON_USEDEP}] )
	polars? ( dev-python/polars[numpy,${PYTHON_USEDEP}] )
	all? ( dev-python/prophet[${PYTHON_USEDEP}] )
	dev? ( dev-python/prophet[${PYTHON_USEDEP}] )
	$(python_gen_cond_dep '<dev-python/protobuf-4.0.0[${PYTHON_USEDEP}]' python3_12)
	$(python_gen_cond_dep '<dev-python/protobuf-4.0.0[${PYTHON_USEDEP}]' python3_12)
	all? ( dev-python/pyarrow[${PYTHON_USEDEP}] )
	dev? ( dev-python/pyarrow[${PYTHON_USEDEP}] )
	all? ( dev-python/pybind11[${PYTHON_USEDEP}] )
	dev? ( dev-python/pybind11[${PYTHON_USEDEP}] )
	all? ( dev-python/pytest[${PYTHON_USEDEP}] )
	dev? ( dev-python/pytest[${PYTHON_USEDEP}] )
	$(python_gen_cond_dep '<=dev-python/ray-2.10[${PYTHON_USEDEP}]' python3_12)
	$(python_gen_cond_dep '<=dev-python/ray-2.10[${PYTHON_USEDEP}]' python3_12)
	all? ( dev-python/scikit-learn[${PYTHON_USEDEP}] )
	dev? ( dev-python/scikit-learn[${PYTHON_USEDEP}] )
	>=dev-python/scipy-1.7.3[${PYTHON_USEDEP}]
	all? ( <dev-python/setuptools-70[${PYTHON_USEDEP}] )
	dev? ( <dev-python/setuptools-70[${PYTHON_USEDEP}] )
	>=dev-python/statsmodels-0.13.2[${PYTHON_USEDEP}]
	all? ( dev-python/supersmoother[${PYTHON_USEDEP}] )
	dev? ( dev-python/supersmoother[${PYTHON_USEDEP}] )
	>=dev-python/threadpoolctl-3[${PYTHON_USEDEP}]
	dev-python/tqdm[${PYTHON_USEDEP}]
	>=dev-python/utilsforecast-0.1.4[${PYTHON_USEDEP}]
	all? ( dev-python/yfinance[${PYTHON_USEDEP}] )
	dev? ( dev-python/yfinance[${PYTHON_USEDEP}] )
	all? ( dev-vcs/pre-commit[${PYTHON_USEDEP}] )
	dev? ( dev-vcs/pre-commit[${PYTHON_USEDEP}] )
"
RDEPEND="${GENERATED_DEPEND}"

distutils_enable_tests pytest