# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
GENERATED_IUSE="all server"
IUSE="${GENERATED_IUSE}"

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/llama-cpp-python/"

LICENSE="MIT"
SLOT="0"
KEYWORDS="amd64 arm64"

GENERATED_DEPEND="${RDEPEND}
	>=dev-python/diskcache-5.6.1[${PYTHON_USEDEP}]
	server? ( >=dev-python/fastapi-0.100.0[${PYTHON_USEDEP}] )
	>=dev-python/jinja2-2.11.3[${PYTHON_USEDEP}]
	all? ( dev-python/llama-cpp-python[dev,server,test,${PYTHON_USEDEP}] )
	>=dev-python/numpy-1.20.0[${PYTHON_USEDEP}]
	server? ( >=dev-python/pydantic-settings-2.0.1[${PYTHON_USEDEP}] )
	server? ( >=dev-python/pyyaml-5.1[${PYTHON_USEDEP}] )
	server? ( >=dev-python/sse-starlette-1.6.1[${PYTHON_USEDEP}] )
	server? ( <dev-python/starlette-context-0.4[${PYTHON_USEDEP}] )
	>=dev-python/typing-extensions-4.5.0[${PYTHON_USEDEP}]
	server? ( >=dev-python/uvicorn-0.22.0[${PYTHON_USEDEP}] )
"
RDEPEND="${GENERATED_DEPEND}"

distutils_enable_tests pytest
BDEPEND+=" test? (
	>=dev-python/black-23.3.0[${PYTHON_USEDEP}]
	>=dev-python/fastapi-0.100.0[${PYTHON_USEDEP}]
	>=dev-python/httpx-0.24.1[${PYTHON_USEDEP}]
	>=dev-python/huggingface-hub-0.23.0[${PYTHON_USEDEP}]
	>=dev-python/mkdocs-1.4.3[${PYTHON_USEDEP}]
	>=dev-python/mkdocs-material-9.1.18[${PYTHON_USEDEP}]
	>=dev-python/mkdocstrings-0.22.0[python,${PYTHON_USEDEP}]
	>=dev-python/pydantic-settings-2.0.1[${PYTHON_USEDEP}]
	>=dev-python/pytest-7.4.0[${PYTHON_USEDEP}]
	>=dev-python/scipy-1.10[${PYTHON_USEDEP}]
	>=dev-python/sse-starlette-1.6.1[${PYTHON_USEDEP}]
	<dev-python/starlette-context-0.4[${PYTHON_USEDEP}]
	>=dev-python/twine-4.0.2[${PYTHON_USEDEP}]
)"
