# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
GENERATED_IUSE="compat lint"
IUSE="${GENERATED_IUSE}"

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/pytest-codspeed/"

LICENSE=""
SLOT="0"
KEYWORDS="amd64 arm64"

REQUIRES_DIST="
	cffi>=1.17.1
	importlib-metadata>=8.5.0; python_version < "3.10"
	mypy~=1.11.2; extra == "lint"
	pytest-benchmark~=5.0.0; extra == "compat"
	pytest-cov~=4.0.0; extra == "test"
	pytest-xdist~=3.6.1; extra == "compat"
	pytest>=3.8
	pytest~=7.0; extra == "test"
	rich>=13.8.1
	ruff~=0.6.5; extra == "lint"
"
GENERATED_RDEPEND="${RDEPEND}
	>=dev-python/cffi-1.17.1[${PYTHON_USEDEP}]
	lint? ( >=dev-python/mypy-1.11.2[${PYTHON_USEDEP}] =dev-python/mypy-1.11*[${PYTHON_USEDEP}] )
	>=dev-python/pytest-3.8[${PYTHON_USEDEP}]
	compat? ( >=dev-python/pytest-benchmark-5.0.0[${PYTHON_USEDEP}] =dev-python/pytest-benchmark-5.0*[${PYTHON_USEDEP}] )
	compat? ( >=dev-python/pytest-xdist-3.6.1[${PYTHON_USEDEP}] =dev-python/pytest-xdist-3.6*[${PYTHON_USEDEP}] )
	>=dev-python/rich-13.8.1[${PYTHON_USEDEP}]
	lint? ( >=dev-python/ruff-0.6.5[${PYTHON_USEDEP}] =dev-python/ruff-0.6*[${PYTHON_USEDEP}] )
"
RDEPEND="${GENERATED_RDEPEND}"

distutils_enable_tests pytest
GENERATED_BDEPEND="${BDEPEND}
	test? (
		>=dev-python/pytest-7.0[${PYTHON_USEDEP}] =dev-python/pytest-7*[${PYTHON_USEDEP}]
		>=dev-python/pytest-cov-4.0.0[${PYTHON_USEDEP}] =dev-python/pytest-cov-4.0*[${PYTHON_USEDEP}]
	)
"
BDEPEND="${GENERATED_BDEPEND}"
