# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
GENERATED_IUSE="cli"
IUSE="${GENERATED_IUSE}"

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/jsf/"

LICENSE=""
SLOT="0"
KEYWORDS="amd64 arm64"

REQUIRES_DIST="
	faker>=15.3.4
	jsonschema>=4.17.3
	pydantic>=2.0.0
	rstr>=3.2.0
	smart-open[http]>=6.3.0
	typer>=0.7.0; extra == "cli"
	typing-extensions>=4.9.0
"
GENERATED_RDEPEND="${RDEPEND}
	>=dev-python/faker-15.3.4[${PYTHON_USEDEP}]
	>=dev-python/jsonschema-4.17.3[${PYTHON_USEDEP}]
	>=dev-python/pydantic-2.0.0[${PYTHON_USEDEP}]
	>=dev-python/rstr-3.2.0[${PYTHON_USEDEP}]
	>=dev-python/smart-open-6.3.0[http,${PYTHON_USEDEP}]
	cli? ( >=dev-python/typer-0.7.0[${PYTHON_USEDEP}] )
	>=dev-python/typing-extensions-4.9.0[${PYTHON_USEDEP}]
"
RDEPEND="${GENERATED_RDEPEND}"

distutils_enable_tests pytest
