# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
PYPI_NO_NORMALIZE=1
GENERATED_IUSE="credssp kerberos"
IUSE="${GENERATED_IUSE}"

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/pypsrp/"

LICENSE="MIT"
SLOT="0"
KEYWORDS="amd64 arm64"

GENERATED_DEPEND="
	dev-python/cryptography[${PYTHON_USEDEP}]
	<dev-python/pyspnego-1.0.0[${PYTHON_USEDEP}]
	kerberos? ( dev-python/pyspnego[kerberos,${PYTHON_USEDEP}] )
	>=dev-python/requests-2.9.1[${PYTHON_USEDEP}]
	credssp? ( >=dev-python/requests-credssp-2.0.0[${PYTHON_USEDEP}] )
"
RDEPEND="${GENERATED_DEPEND}"

distutils_enable_tests pytest