# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
PYPI_NO_NORMALIZE=1
GENERATED_IUSE="debug graphql http validation"
IUSE="${GENERATED_IUSE}"

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/datamodel-code-generator/"

LICENSE="MIT"
SLOT="0"
KEYWORDS="amd64 arm64"

GENERATED_DEPEND="${PYTHON_DEPS}
	<dev-python/argcomplete-4.0[${PYTHON_USEDEP}]
	>=dev-python/black-19.10_beta0[${PYTHON_USEDEP}]
	<dev-python/genson-2.0[${PYTHON_USEDEP}]
	graphql? ( <dev-python/graphql-core-4.0.0[${PYTHON_USEDEP}] )
	http? ( dev-python/httpx[${PYTHON_USEDEP}] )
	<dev-python/inflect-6.0[${PYTHON_USEDEP}]
	<dev-python/isort-6.0[${PYTHON_USEDEP}]
	<dev-python/jinja2-4.0[${PYTHON_USEDEP}]
	validation? ( <dev-python/openapi-spec-validator-0.7.0[${PYTHON_USEDEP}] )
	dev-python/packaging[${PYTHON_USEDEP}]
	validation? ( >=dev-python/prance-0.18.2[${PYTHON_USEDEP}] )
	!=dev-python/pydantic-2.4.0[email,${PYTHON_USEDEP}]
	!=dev-python/pydantic-2.4.0[email,${PYTHON_USEDEP}]
	$(python_gen_cond_dep '!=dev-python/pydantic-2.0.0[email,${PYTHON_USEDEP}]' python3_13{,t})
	debug? ( <dev-python/pysnooper-2.0.0[${PYTHON_USEDEP}] )
	>=dev-python/pyyaml-6.0.1[${PYTHON_USEDEP}]
"
RDEPEND="${GENERATED_DEPEND}"

distutils_enable_tests pytest
