# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
PYPI_NO_NORMALIZE=1
GENERATED_IUSE="all dev doc extra ml style test viz"
IUSE="${GENERATED_IUSE}"

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/dipy/"

LICENSE=""
SLOT="0"
KEYWORDS="amd64 arm64"

GENERATED_DEPEND="
	test? ( dev-python/asv[${PYTHON_USEDEP}] )
	extra? ( dev-python/boto3[${PYTHON_USEDEP}] )
	dev? ( dev-python/build[${PYTHON_USEDEP}] )
	test? ( dev-python/codecov[${PYTHON_USEDEP}] )
	test? ( dev-python/coverage[${PYTHON_USEDEP}] )
	test? ( dev-python/coveralls[${PYTHON_USEDEP}] )
	extra? ( dev-python/cvxpy[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/cython-0.29.35[${PYTHON_USEDEP}] )
	all? ( dev-python/dipy[dev,doc,extra,ml,style,test,viz,${PYTHON_USEDEP}] )
	extra? ( dev-python/dipy[ml,viz,${PYTHON_USEDEP}] )
	viz? ( >=dev-python/fury-0.10.0[${PYTHON_USEDEP}] )
	doc? ( >=dev-python/grg-sphinx-theme-0.4.0[${PYTHON_USEDEP}] )
	>=dev-python/h5py-3.1.0[${PYTHON_USEDEP}]
	doc? ( dev-python/jinja2[${PYTHON_USEDEP}] )
	viz? ( dev-python/matplotlib[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/meson-python-0.13[${PYTHON_USEDEP}] )
	>=dev-python/nibabel-3.0.0[${PYTHON_USEDEP}]
	dev? ( dev-python/ninja[${PYTHON_USEDEP}] )
	>=dev-python/numpy-1.22.4[${PYTHON_USEDEP}]
	dev? ( >=dev-python/numpy-1.22.4[${PYTHON_USEDEP}] )
	doc? ( dev-python/numpydoc[${PYTHON_USEDEP}] )
	>=dev-python/packaging-21[${PYTHON_USEDEP}]
	dev? ( >=dev-python/packaging-21[${PYTHON_USEDEP}] )
	ml? ( dev-python/pandas[${PYTHON_USEDEP}] )
	test? ( dev-python/pytest[${PYTHON_USEDEP}] )
	style? ( dev-python/ruff[${PYTHON_USEDEP}] )
	extra? ( dev-python/scikit-image[${PYTHON_USEDEP}] )
	ml? ( dev-python/scikit-learn[${PYTHON_USEDEP}] )
	>=dev-python/scipy-1.8[${PYTHON_USEDEP}]
	dev? ( ~dev-python/setuptools-69.5[${PYTHON_USEDEP}] )
	doc? ( >=dev-python/sphinx-7.2.6[${PYTHON_USEDEP}] )
	doc? ( dev-python/sphinx-design[${PYTHON_USEDEP}] )
	doc? ( >=dev-python/sphinx-gallery-0.10.0[${PYTHON_USEDEP}] )
	doc? ( dev-python/sphinxcontrib-bibtex[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/spin-0.5[${PYTHON_USEDEP}] )
	ml? ( >=dev-python/statsmodels-0.14.0[${PYTHON_USEDEP}] )
	ml? ( dev-python/tables[${PYTHON_USEDEP}] )
	ml? ( dev-python/tensorflow[${PYTHON_USEDEP}] )
	doc? ( dev-python/texext[${PYTHON_USEDEP}] )
	doc? ( >=dev-python/tomli-2.0.1[${PYTHON_USEDEP}] )
	ml? ( dev-python/torch[${PYTHON_USEDEP}] )
	>=dev-python/tqdm-4.30.0[${PYTHON_USEDEP}]
	>=dev-python/trx-python-0.2.9[${PYTHON_USEDEP}]
	dev? ( dev-python/wheel[${PYTHON_USEDEP}] )
	style? ( dev-vcs/pre-commit[${PYTHON_USEDEP}] )
"
RDEPEND="${GENERATED_DEPEND}"

distutils_enable_tests pytest