# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
GENERATED_IUSE="docs test"
IUSE="${GENERATED_IUSE}"

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/jupyterlite-sphinx/"

LICENSE=""
SLOT="0"
KEYWORDS="amd64 arm64"

REQUIRES_DIST="
	docutils
	hatch; extra == 'dev'
	jupyter-server
	jupyterlab-server
	jupyterlite-core<0.6,>=0.2
	jupyterlite-xeus<4,>=0.1.8; extra == 'docs'
	jupytext
	myst-parser; extra == 'docs'
	nbformat
	pydata-sphinx-theme; extra == 'docs'
	sphinx>=4
"
GENERATED_RDEPEND="${RDEPEND}
	dev-python/docutils[${PYTHON_USEDEP}]
	dev-python/jupyter-server[${PYTHON_USEDEP}]
	dev-python/jupyterlab-server[${PYTHON_USEDEP}]
	>=dev-python/jupyterlite-core-0.2[${PYTHON_USEDEP}] <dev-python/jupyterlite-core-0.6[${PYTHON_USEDEP}]
	docs? ( >=dev-python/jupyterlite-xeus-0.1.8[${PYTHON_USEDEP}] <dev-python/jupyterlite-xeus-4[${PYTHON_USEDEP}] )
	dev-python/jupytext[${PYTHON_USEDEP}]
	docs? ( dev-python/myst-parser[${PYTHON_USEDEP}] )
	dev-python/nbformat[${PYTHON_USEDEP}]
	docs? ( dev-python/pydata-sphinx-theme[${PYTHON_USEDEP}] )
	>=dev-python/sphinx-4[${PYTHON_USEDEP}]
"
RDEPEND="${GENERATED_RDEPEND}"

distutils_enable_tests pytest
GENERATED_BDEPEND="${BDEPEND}
	test? (
		dev-python/hatch[${PYTHON_USEDEP}]
	)
"
BDEPEND="${GENERATED_BDEPEND}"
