# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
GENERATED_IUSE="adlfs azureml connectors-aws connectors-azure connectors-gcp connectors-kubernetes gcsfs s3fs sagemaker secrets-aws secrets-azure secrets-gcp secrets-hashicorp server templates test vertex"
IUSE="${GENERATED_IUSE}"

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE="
  https://pypi.org/project/zenml/"

LICENSE="Apache-2.0"
SLOT="0"
KEYWORDS="amd64 arm64"

REQUIRES_DIST="
	Jinja2; extra == 'server'
	adlfs>=2021.10.0; extra == 'adlfs'
	alembic<1.9.0,>=1.8.1
	aws-profile-manager>=0.5.0; extra == 'connectors-aws'
	azure-ai-ml==1.23.1; extra == 'azureml'
	azure-identity>=1.4.0; extra == 'secrets-azure' or extra == 'connectors-azure'
	azure-keyvault-secrets>=4.0.0; extra == 'secrets-azure'
	azure-mgmt-containerregistry>=10.0.0; extra == 'connectors-azure'
	azure-mgmt-containerservice>=20.0.0; extra == 'connectors-azure'
	azure-mgmt-resource>=21.0.0; extra == 'connectors-azure'
	azure-mgmt-storage>=20.0.0; extra == 'connectors-azure'
	azure-storage-blob>=12.0.0; extra == 'connectors-azure'
	bandit<2.0.0,>=1.7.5; extra == 'dev'
	bcrypt==4.0.1
	boto3>=1.16.0; extra == 'secrets-aws' or extra == 'connectors-aws'
	click<8.1.4,>=8.0.1
	cloudpickle<3,>=2.0.0
	copier>=8.1.0; extra == 'templates'
	coverage[toml]<6.0,>=5.5; extra == 'dev'
	darglint<2.0.0,>=1.8.1; extra == 'dev'
	distro<2.0.0,>=1.6.0
	docker<7.2.0,>=7.1.0
	fastapi<=0.110,>=0.100; extra == 'server'
	gcsfs>=2022.11.0; extra == 'gcsfs'
	gitpython<4.0.0,>=3.1.18
	google-cloud-aiplatform>=1.34.0; extra == 'vertex'
	google-cloud-artifact-registry>=1.11.3; extra == 'connectors-gcp'
	google-cloud-container>=2.21.0; extra == 'connectors-gcp'
	google-cloud-secret-manager>=2.12.5; extra == 'secrets-gcp'
	google-cloud-storage>=2.9.0; extra == 'connectors-gcp'
	hvac>=0.11.2; extra == 'secrets-hashicorp'
	hypothesis<7.0.0,>=6.43.1; extra == 'dev'
	importlib_metadata<=7.0.0; python_version < '3.10'
	ipinfo>=4.4.3; extra == 'server'
	itsdangerous<2.3.0,>=2.2.0; extra == 'server'
	jinja2-time<0.3.0,>=0.2.0; extra == 'templates'
	kfp>=2.6.0; extra == 'vertex'
	kubernetes>=18.20.0; extra == 'connectors-kubernetes' or extra == 'connectors-aws' or extra == 'connectors-gcp' or extra == 'connectors-azure'
	maison<2.0; extra == 'dev'
	mike<2.0.0,>=1.1.2; extra == 'dev'
	mkdocs-awesome-pages-plugin<3.0.0,>=2.6.1; extra == 'dev'
	mkdocs-material<9.0.0,>=8.1.7; extra == 'dev'
	mkdocs<2.0.0,>=1.2.3; extra == 'dev'
	mkdocstrings<0.18.0,>=0.17.0; extra == 'dev'
	mypy==1.7.1; extra == 'dev'
	orjson<3.11.0,>=3.10.0; extra == 'server'
	packaging>=24.1
	passlib[bcrypt]<1.8.0,>=1.7.4
	psutil>=5.0.0
	pydantic-settings
	pydantic<2.9,>=2.8
	pyjwt[crypto]==2.7.*; extra == 'server'
	pyment<0.4.0,>=0.3.3; extra == 'dev'
	pymysql<1.2.0,>=1.1.1
	pytest-clarity<2.0.0,>=1.0.1; extra == 'dev'
	pytest-instafail>=0.5.0; extra == 'dev'
	pytest-mock<4.0.0,>=3.6.1; extra == 'dev'
	pytest-randomly<4.0.0,>=3.10.1; extra == 'dev'
	pytest-rerunfailures>=13.0; extra == 'dev'
	pytest-split<0.9.0,>=0.8.1; extra == 'dev'
	pytest<8.0.0,>=7.4.0; extra == 'dev'
	python-dateutil<3.0.0,>=2.8.1
	python-multipart<0.1.0,>=0.0.9; extra == 'server'
	pyyaml-include<2.0; extra == 'templates'
	pyyaml>=6.0.1
	requests<3.0.0,>=2.27.11; extra == 'connectors-azure'
	rich[jupyter]>=12.0.0
	ruff>=0.1.7; extra == 'templates' or extra == 'dev'
	s3fs>=2022.11.0; extra == 's3fs'
	sagemaker>=2.199.0; extra == 'sagemaker'
	secure<0.4.0,>=0.3.0; extra == 'server'
	setuptools
	sqlalchemy<3.0.0,>=2.0.0
	sqlalchemy_utils
	sqlmodel==0.0.18
	tldextract<5.2.0,>=5.1.0; extra == 'server'
	tox<4.0.0,>=3.24.3; extra == 'dev'
	types-Markdown<4.0.0,>=3.3.6; extra == 'dev'
	types-Pillow<10.0.0,>=9.2.1; extra == 'dev'
	types-PyMySQL<2.0.0,>=1.0.4; extra == 'dev'
	types-PyYAML<7.0.0,>=6.0.0; extra == 'dev'
	types-certifi<2022.0.0.0,>=2021.10.8.0; extra == 'dev'
	types-croniter<2.0.0,>=1.0.2; extra == 'dev'
	types-futures<4.0.0,>=3.3.1; extra == 'dev'
	types-paramiko>=3.4.0; extra == 'dev'
	types-passlib<2.0.0,>=1.7.7; extra == 'dev'
	types-protobuf<4.0.0,>=3.18.0; extra == 'dev'
	types-psutil<6.0.0,>=5.8.13; extra == 'dev'
	types-python-dateutil<3.0.0,>=2.8.2; extra == 'dev'
	types-python-slugify<6.0.0,>=5.0.2; extra == 'dev'
	types-redis<5.0.0,>=4.1.19; extra == 'dev'
	types-requests<3.0.0,>=2.27.11; extra == 'dev'
	types-setuptools<58.0.0,>=57.4.2; extra == 'dev'
	types-six<2.0.0,>=1.16.2; extra == 'dev'
	types-termcolor<2.0.0,>=1.1.2; extra == 'dev'
	typing-extensions>=3.7.4; extra == 'dev'
	uvicorn[standard]>=0.17.5; extra == 'server'
	yamlfix<2.0.0,>=1.16.0; extra == 'dev'
"
GENERATED_RDEPEND="${RDEPEND}
	adlfs? ( >=dev-python/adlfs-2021.10.0[${PYTHON_USEDEP}] )
	>=dev-python/alembic-1.8.1[${PYTHON_USEDEP}] <dev-python/alembic-1.9.0[${PYTHON_USEDEP}]
	connectors-aws? ( >=dev-python/aws-profile-manager-0.5.0[${PYTHON_USEDEP}] )
	azureml? ( ~dev-python/azure-ai-ml-1.23.1[${PYTHON_USEDEP}] )
	connectors-azure? ( >=dev-python/azure-identity-1.4.0[${PYTHON_USEDEP}] ) secrets-azure? ( >=dev-python/azure-identity-1.4.0[${PYTHON_USEDEP}] )
	secrets-azure? ( >=dev-python/azure-keyvault-secrets-4.0.0[${PYTHON_USEDEP}] )
	connectors-azure? ( >=dev-python/azure-mgmt-containerregistry-10.0.0[${PYTHON_USEDEP}] )
	connectors-azure? ( >=dev-python/azure-mgmt-containerservice-20.0.0[${PYTHON_USEDEP}] )
	connectors-azure? ( >=dev-python/azure-mgmt-resource-21.0.0[${PYTHON_USEDEP}] )
	connectors-azure? ( >=dev-python/azure-mgmt-storage-20.0.0[${PYTHON_USEDEP}] )
	connectors-azure? ( >=dev-python/azure-storage-blob-12.0.0[${PYTHON_USEDEP}] )
	~dev-python/bcrypt-4.0.1[${PYTHON_USEDEP}]
	secrets-aws? ( >=dev-python/boto3-1.16.0[${PYTHON_USEDEP}] ) connectors-aws? ( >=dev-python/boto3-1.16.0[${PYTHON_USEDEP}] )
	>=dev-python/click-8.0.1[${PYTHON_USEDEP}] <dev-python/click-8.1.4[${PYTHON_USEDEP}]
	>=dev-python/cloudpickle-2.0.0[${PYTHON_USEDEP}] <dev-python/cloudpickle-3[${PYTHON_USEDEP}]
	templates? ( >=dev-python/copier-8.1.0[${PYTHON_USEDEP}] )
	>=dev-python/distro-1.6.0[${PYTHON_USEDEP}] <dev-python/distro-2.0.0[${PYTHON_USEDEP}]
	>=dev-python/docker-7.1.0[${PYTHON_USEDEP}] <dev-python/docker-7.2.0[${PYTHON_USEDEP}]
	server? ( >=dev-python/fastapi-0.100[${PYTHON_USEDEP}] <=dev-python/fastapi-0.110[${PYTHON_USEDEP}] )
	gcsfs? ( >=dev-python/gcsfs-2022.11.0[${PYTHON_USEDEP}] )
	>=dev-python/gitpython-3.1.18[${PYTHON_USEDEP}] <dev-python/gitpython-4.0.0[${PYTHON_USEDEP}]
	vertex? ( >=dev-python/google-cloud-aiplatform-1.34.0[${PYTHON_USEDEP}] )
	connectors-gcp? ( >=dev-python/google-cloud-artifact-registry-1.11.3[${PYTHON_USEDEP}] )
	connectors-gcp? ( >=dev-python/google-cloud-container-2.21.0[${PYTHON_USEDEP}] )
	secrets-gcp? ( >=dev-python/google-cloud-secret-manager-2.12.5[${PYTHON_USEDEP}] )
	connectors-gcp? ( >=dev-python/google-cloud-storage-2.9.0[${PYTHON_USEDEP}] )
	secrets-hashicorp? ( >=dev-python/hvac-0.11.2[${PYTHON_USEDEP}] )
	server? ( >=dev-python/ipinfo-4.4.3[${PYTHON_USEDEP}] )
	server? ( >=dev-python/itsdangerous-2.2.0[${PYTHON_USEDEP}] <dev-python/itsdangerous-2.3.0[${PYTHON_USEDEP}] )
	server? ( dev-python/jinja2[${PYTHON_USEDEP}] )
	templates? ( >=dev-python/jinja2-time-0.2.0[${PYTHON_USEDEP}] <dev-python/jinja2-time-0.3.0[${PYTHON_USEDEP}] )
	vertex? ( >=dev-python/kfp-2.6.0[${PYTHON_USEDEP}] )
	connectors-gcp? ( >=dev-python/kubernetes-18.20.0[${PYTHON_USEDEP}] ) connectors-azure? ( >=dev-python/kubernetes-18.20.0[${PYTHON_USEDEP}] ) connectors-kubernetes? ( >=dev-python/kubernetes-18.20.0[${PYTHON_USEDEP}] ) connectors-aws? ( >=dev-python/kubernetes-18.20.0[${PYTHON_USEDEP}] )
	server? ( >=dev-python/orjson-3.10.0[${PYTHON_USEDEP}] <dev-python/orjson-3.11.0[${PYTHON_USEDEP}] )
	>=dev-python/packaging-24.1[${PYTHON_USEDEP}]
	>=dev-python/passlib-1.7.4[bcrypt,${PYTHON_USEDEP}] <dev-python/passlib-1.8.0[bcrypt,${PYTHON_USEDEP}]
	>=dev-python/psutil-5.0.0[${PYTHON_USEDEP}]
	>=dev-python/pydantic-2.8[${PYTHON_USEDEP}] <dev-python/pydantic-2.9[${PYTHON_USEDEP}]
	dev-python/pydantic-settings[${PYTHON_USEDEP}]
	server? ( =dev-python/pyjwt-2.7*[crypto,${PYTHON_USEDEP}] )
	>=dev-python/pymysql-1.1.1[${PYTHON_USEDEP}] <dev-python/pymysql-1.2.0[${PYTHON_USEDEP}]
	>=dev-python/python-dateutil-2.8.1[${PYTHON_USEDEP}] <dev-python/python-dateutil-3.0.0[${PYTHON_USEDEP}]
	server? ( >=dev-python/python-multipart-0.0.9[${PYTHON_USEDEP}] <dev-python/python-multipart-0.1.0[${PYTHON_USEDEP}] )
	>=dev-python/pyyaml-6.0.1[${PYTHON_USEDEP}]
	templates? ( <dev-python/pyyaml-include-2.0[${PYTHON_USEDEP}] )
	connectors-azure? ( >=dev-python/requests-2.27.11[${PYTHON_USEDEP}] <dev-python/requests-3.0.0[${PYTHON_USEDEP}] )
	>=dev-python/rich-12.0.0[jupyter,${PYTHON_USEDEP}]
	s3fs? ( >=dev-python/s3fs-2022.11.0[${PYTHON_USEDEP}] )
	sagemaker? ( >=dev-python/sagemaker-2.199.0[${PYTHON_USEDEP}] )
	server? ( >=dev-python/secure-0.3.0[${PYTHON_USEDEP}] <dev-python/secure-0.4.0[${PYTHON_USEDEP}] )
	dev-python/setuptools[${PYTHON_USEDEP}]
	>=dev-python/sqlalchemy-2.0.0[${PYTHON_USEDEP}] <dev-python/sqlalchemy-3.0.0[${PYTHON_USEDEP}]
	dev-python/sqlalchemy-utils[${PYTHON_USEDEP}]
	~dev-python/sqlmodel-0.0.18[${PYTHON_USEDEP}]
	server? ( >=dev-python/tldextract-5.1.0[${PYTHON_USEDEP}] <dev-python/tldextract-5.2.0[${PYTHON_USEDEP}] )
	server? ( >=dev-python/uvicorn-0.17.5[standard,${PYTHON_USEDEP}] )
"
RDEPEND="${GENERATED_RDEPEND}"

distutils_enable_tests pytest
GENERATED_BDEPEND="${BDEPEND}
	test? (
		>=dev-python/bandit-1.7.5[${PYTHON_USEDEP}] <dev-python/bandit-2.0.0[${PYTHON_USEDEP}]
		>=dev-python/coverage-5.5[toml,${PYTHON_USEDEP}] <dev-python/coverage-6.0[toml,${PYTHON_USEDEP}]
		>=dev-python/darglint-1.8.1[${PYTHON_USEDEP}] <dev-python/darglint-2.0.0[${PYTHON_USEDEP}]
		>=dev-python/hypothesis-6.43.1[${PYTHON_USEDEP}] <dev-python/hypothesis-7.0.0[${PYTHON_USEDEP}]
		<dev-python/maison-2.0[${PYTHON_USEDEP}]
		>=dev-python/mike-1.1.2[${PYTHON_USEDEP}] <dev-python/mike-2.0.0[${PYTHON_USEDEP}]
		>=dev-python/mkdocs-1.2.3[${PYTHON_USEDEP}] <dev-python/mkdocs-2.0.0[${PYTHON_USEDEP}]
		>=dev-python/mkdocs-awesome-pages-plugin-2.6.1[${PYTHON_USEDEP}] <dev-python/mkdocs-awesome-pages-plugin-3.0.0[${PYTHON_USEDEP}]
		>=dev-python/mkdocs-material-8.1.7[${PYTHON_USEDEP}] <dev-python/mkdocs-material-9.0.0[${PYTHON_USEDEP}]
		>=dev-python/mkdocstrings-0.17.0[${PYTHON_USEDEP}] <dev-python/mkdocstrings-0.18.0[${PYTHON_USEDEP}]
		~dev-python/mypy-1.7.1[${PYTHON_USEDEP}]
		>=dev-python/pyment-0.3.3[${PYTHON_USEDEP}] <dev-python/pyment-0.4.0[${PYTHON_USEDEP}]
		>=dev-python/pytest-7.4.0[${PYTHON_USEDEP}] <dev-python/pytest-8.0.0[${PYTHON_USEDEP}]
		>=dev-python/pytest-clarity-1.0.1[${PYTHON_USEDEP}] <dev-python/pytest-clarity-2.0.0[${PYTHON_USEDEP}]
		>=dev-python/pytest-instafail-0.5.0[${PYTHON_USEDEP}]
		>=dev-python/pytest-mock-3.6.1[${PYTHON_USEDEP}] <dev-python/pytest-mock-4.0.0[${PYTHON_USEDEP}]
		>=dev-python/pytest-randomly-3.10.1[${PYTHON_USEDEP}] <dev-python/pytest-randomly-4.0.0[${PYTHON_USEDEP}]
		>=dev-python/pytest-rerunfailures-13.0[${PYTHON_USEDEP}]
		>=dev-python/pytest-split-0.8.1[${PYTHON_USEDEP}] <dev-python/pytest-split-0.9.0[${PYTHON_USEDEP}]
		>=dev-python/ruff-0.1.7[${PYTHON_USEDEP}] templates? ( >=dev-python/ruff-0.1.7[${PYTHON_USEDEP}] )
		>=dev-python/tox-3.24.3[${PYTHON_USEDEP}] <dev-python/tox-4.0.0[${PYTHON_USEDEP}]
		>=dev-python/types-certifi-2021.10.8.0[${PYTHON_USEDEP}] <dev-python/types-certifi-2022.0.0.0[${PYTHON_USEDEP}]
		>=dev-python/types-croniter-1.0.2[${PYTHON_USEDEP}] <dev-python/types-croniter-2.0.0[${PYTHON_USEDEP}]
		>=dev-python/types-futures-3.3.1[${PYTHON_USEDEP}] <dev-python/types-futures-4.0.0[${PYTHON_USEDEP}]
		>=dev-python/types-markdown-3.3.6[${PYTHON_USEDEP}] <dev-python/types-markdown-4.0.0[${PYTHON_USEDEP}]
		>=dev-python/types-paramiko-3.4.0[${PYTHON_USEDEP}]
		>=dev-python/types-passlib-1.7.7[${PYTHON_USEDEP}] <dev-python/types-passlib-2.0.0[${PYTHON_USEDEP}]
		>=dev-python/types-pillow-9.2.1[${PYTHON_USEDEP}] <dev-python/types-pillow-10.0.0[${PYTHON_USEDEP}]
		>=dev-python/types-protobuf-3.18.0[${PYTHON_USEDEP}] <dev-python/types-protobuf-4.0.0[${PYTHON_USEDEP}]
		>=dev-python/types-psutil-5.8.13[${PYTHON_USEDEP}] <dev-python/types-psutil-6.0.0[${PYTHON_USEDEP}]
		>=dev-python/types-pymysql-1.0.4[${PYTHON_USEDEP}] <dev-python/types-pymysql-2.0.0[${PYTHON_USEDEP}]
		>=dev-python/types-python-dateutil-2.8.2[${PYTHON_USEDEP}] <dev-python/types-python-dateutil-3.0.0[${PYTHON_USEDEP}]
		>=dev-python/types-python-slugify-5.0.2[${PYTHON_USEDEP}] <dev-python/types-python-slugify-6.0.0[${PYTHON_USEDEP}]
		>=dev-python/types-pyyaml-6.0.0[${PYTHON_USEDEP}] <dev-python/types-pyyaml-7.0.0[${PYTHON_USEDEP}]
		>=dev-python/types-redis-4.1.19[${PYTHON_USEDEP}] <dev-python/types-redis-5.0.0[${PYTHON_USEDEP}]
		>=dev-python/types-requests-2.27.11[${PYTHON_USEDEP}] <dev-python/types-requests-3.0.0[${PYTHON_USEDEP}]
		>=dev-python/types-setuptools-57.4.2[${PYTHON_USEDEP}] <dev-python/types-setuptools-58.0.0[${PYTHON_USEDEP}]
		>=dev-python/types-six-1.16.2[${PYTHON_USEDEP}] <dev-python/types-six-2.0.0[${PYTHON_USEDEP}]
		>=dev-python/types-termcolor-1.1.2[${PYTHON_USEDEP}] <dev-python/types-termcolor-2.0.0[${PYTHON_USEDEP}]
		>=dev-python/typing-extensions-3.7.4[${PYTHON_USEDEP}]
		>=dev-python/yamlfix-1.16.0[${PYTHON_USEDEP}] <dev-python/yamlfix-2.0.0[${PYTHON_USEDEP}]
	)
"
BDEPEND="${GENERATED_BDEPEND}"
